### ISSUE TITLE
示例代码simple中，应该不止抓取人民日报和新华社吧

### ISSUE THREAD

**Issue by DanerHeart** [nghuyong/WeiboSpider#10]
看了一下代码，information_item['_id']，在持续增加，应该会遍历所有用户吧，所以应该不止爬取新华社和人民日报，请问是这样吗

**Comment by nghuyong** [comment]
不会啊，应该就是只抓取新华社和人民日报。
具体可以取你的数据库看一下，抓取了哪些数据。

**Comment by LiuBaoxi** [comment]
我刚刚跑了一遍，确实是抓两个站点，我又看了一遍master的代码，感觉和我想的不一样啊，难道master也只抓两个网站吗，明明ID在增加。

**Comment by LiuBaoxi** [comment]
抱歉，我明白了，start_uids才是循环爬的关键，应该加到这里才能实现遍历

**Comment by nghuyong** [comment]
OK
