### ISSUE TITLE
如何在Middlewares中实现动态获取IP

### ISSUE THREAD

**Issue by 112798** [nghuyong/WeiboSpider#100]
在进行数据爬取使用代理IP的时候，需要通过从代理IP服务商提供的API获取代理IP，但相应的对于提取代理的频率也有相应的限制（我使用的是蘑菇代理）；所以不能在每个request到达middlewares的时候都向API发送一个GET请求来获取代理（会导致请求代理的频率过高被代理服务商封禁）。  
能否在middlewares中单独实现一个线程？或者进程，动态的定时更新代理IP；我尝试着在middlewares中添加板块实现类似的功能，但是并没有很好地兼容Scrapy框架的运行特点，现在只能单独写一个脚本将获取到的代理存入数据库或者本地临时文件中；请问能否将这个独立脚本的功能写入Scrapy的某个框架模块中？

**Comment by nghuyong** [comment]
我是专门自己写了一个代理池，代理池会按照代理服务商的要求频率拉去代理并维护代理（添加，验证是否可用，不可用删除，按速度排序）等，然后在middlewares中直接去代理池拿IP。
你这个建议很不错，会考虑开放代理池的code

**Comment by 112798** [comment]
了解了，我会尝试搭建自己的代理池；  
多谢！
