### ISSUE TITLE
Selenium support for PhantomJS has been deprecated

### ISSUE THREAD

**Issue by SyuuGenn** [nghuyong/WeiboSpider#101]
建构账号池失败，查了一下代码问题出在`username = wait.until(EC.presence_of_element_located((By.ID, 'loginName')))`。

> ---------------------------------------------------------------------------
TimeoutException                          Traceback (most recent call last)
<ipython-input-33-ea3eda1314a3> in <module>
----> 1 username = wait.until(EC.presence_of_element_located((By.ID, 'loginName')))

//anaconda3/lib/python3.7/site-packages/selenium/webdriver/support/wait.py in until(self, method, message)
     78             if time.time() > end_time:
     79                 break
---> 80         raise TimeoutException(message, screen, stacktrace)
     81 
     82     def until_not(self, method, message=''):

TimeoutException: Message: 
Screenshot: available via screen

在`browser = webdriver.PhantomJS()`时虽然没有报错，但是警告Selenium support for PhantomJS has been deprecated。请问这个问题应该如何解决？

**Comment by nghuyong** [comment]
可以切换到Chrome浏览器，会尽快更新代码

**Comment by banyiluoyun** [comment]
要不直接安装一个phantomjs？是不是也能解决这个问题？

**Comment by nghuyong** [comment]
对，也可以解决。遵循readme安装一下phantomjs即可
