### ISSUE TITLE
clone defeated

### ISSUE THREAD

**Issue by ashin010** [nghuyong/WeiboSpider#102]
![1](https://user-images.githubusercontent.com/50632773/66150367-02462880-e5e3-11e9-9f7c-7b147cd4f79a.png)

**Comment by nghuyong** [comment]
你需要先配置GitHub的公钥，可自行百度

**Comment by ashin010** [comment]
got it. thank u

HuYong <notifications@github.com>于2019年10月5日 周六上午8:12写道：
