### ISSUE TITLE
服务器爬取失败问题

### ISSUE THREAD

**Issue by WAng91An** [nghuyong/WeiboSpider#103]
我在本地跑此脚本非常顺利，帐号池里面的账号全部都是success，但是放到服务器上爬，过了不到2分钟，账号的status全部是error了。并且http_code = 302，这是为什么啊？

**Comment by nghuyong** [comment]
你在服务器上重新登陆了帐号吗？

**Comment by WAng91An** [comment]
我在服务器上装了mongodb服务，先跑了一遍login.py，跑完之后获取到了cookie，而且status都是success。但是一跑爬虫脚本 就回error


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: HuYong <notifications@github.com&gt;
发送时间: 2019年10月7日 09:42
收件人: nghuyong/WeiboSpider <WeiboSpider@noreply.github.com&gt;
抄送: Wang Ruiqian <1027700603@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[nghuyong/WeiboSpider] 服务器爬取失败问题 (#103)




你在服务器上重新登陆了帐号吗？

**Comment by nghuyong** [comment]
额，我建议你把本地跑出来的cookie导出，然后导入到服务器上，在运行爬虫。不要在服务器上登陆了。因为存在异地（ip不同）登陆的问题，可能帐号就异常了。

**Comment by WAng91An** [comment]
刚刚试了，一下还是那样。本地获取cookie，服务器上跑也不灵




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: HuYong <notifications@github.com&gt;
发送时间: 2019年10月7日 10:05
收件人: nghuyong/WeiboSpider <WeiboSpider@noreply.github.com&gt;
抄送: Wang Ruiqian <1027700603@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[nghuyong/WeiboSpider] 服务器爬取失败问题 (#103)




额，我建议你把本地跑出来的cookie导出，然后导入到服务器上，在运行爬虫。不要在服务器上登陆了。因为存在异地（ip不同）登陆的问题，可能帐号就异常了。

**Comment by banyiluoyun** [comment]
> 我在本地跑此脚本非常顺利，帐号池里面的账号全部都是success，但是放到服务器上爬，过了不到2分钟，账号的status全部是error了。并且http_code = 302，这是为什么啊？

你好，请问你的帐号在哪里购买的。。。。。我购买的帐号全都需要验证登录，不知道怎么回事

**Comment by WAng91An** [comment]
Issue里面提到三个网址，最后一个买的0.2一个


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: banyiluoyun <notifications@github.com&gt;
发送时间: 2019年10月11日 15:13
收件人: nghuyong/WeiboSpider <WeiboSpider@noreply.github.com&gt;
抄送: Wang Ruiqian <1027700603@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[nghuyong/WeiboSpider] 服务器爬取失败问题 (#103)



 
我在本地跑此脚本非常顺利，帐号池里面的账号全部都是success，但是放到服务器上爬，过了不到2分钟，账号的status全部是error了。并且http_code = 302，这是为什么啊？
  
你好，请问你的帐号在哪里购买的。。。。。我购买的帐号全都需要验证登录，不知道怎么回事
