### ISSUE TITLE
这个能爬取指定的微博吗

### ISSUE THREAD

**Issue by YangMyuan** [nghuyong/WeiboSpider#105]
有的用户只能用到其中的一条微博

**Comment by nghuyong** [comment]
可以抓取，稍微修改一下代码即可

**Comment by YangMyuan** [comment]
谢谢我试一下！是将UID那里改一下么
还有一个问题，项目下载下来，weibo_spider里面from sina.items import TweetsItem, InformationItem, RelationshipsItem, CommentItem
from sina.spiders.utils import time_fix, extract_weibo_content, extract_comment_content


这两句总是显示
cannot find reference

在 2019-10-09 16:09:23，"HuYong" <notifications@github.com> 写道：


可以抓取，稍微修改一下代码即可
