### ISSUE TITLE
<class 'ValueError'>: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by SyuuGenn** [nghuyong/WeiboSpider#109]
你好，爬虫运行一段时间后一直跳下面的错误：

> 2019-10-26 05:31:51 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://weibo.cn/comment/GD7Ne1OVd?page=61> (failed 3 times): An error occurred while connecting: [Failure instance: Traceback: <class 'ValueError'>: filedescriptor out of range in select()
/Users/yuanzhou/opt/anaconda3/lib/python3.7/site-packages/twisted/internet/base.py:1283:run
/Users/yuanzhou/opt/anaconda3/lib/python3.7/site-packages/twisted/internet/base.py:1295:mainLoop
/Users/yuanzhou/opt/anaconda3/lib/python3.7/site-packages/twisted/internet/selectreactor.py:106:doSelect
/Users/yuanzhou/opt/anaconda3/lib/python3.7/site-packages/twisted/internet/selectreactor.py:88:_preenDescriptors
--- <exception caught here> ---
/Users/yuanzhou/opt/anaconda3/lib/python3.7/site-packages/twisted/internet/selectreactor.py:85:_preenDescriptors
].

请问这是什么原因啊？我用的是Mac OS系统。

**Comment by nghuyong** [comment]
我没遇到你这个问题，也无法给你复现这个问题
https://github.com/andymccurdy/redis-py/issues/1115
可能是redis相关的错误，你可以参考上面这个链接

**Comment by SyuuGenn** [comment]
感谢回复。但是我的scrapy代码中并不涉及redis，我是自己建了一个代理ip池，从http://0.0.0.0:9102/random/中随机获取一个代理IP。中间件的代码是：
`class IPProxyMiddleware(object):

    def fetch_proxy(self):
        return requests.get("http://0.0.0.0:9102/random/").text

    def process_request(self, request, spider):
        proxy_data = self.fetch_proxy()
        current_proxy = f'http://{proxy_data}'
        spider.logger.debug(f"当前代理IP:{current_proxy}")
        request.meta['proxy'] = current_proxy`

这部分代码没什么问题吧？

**Comment by nghuyong** [comment]
requests.get("http://0.0.0.0:9102/random/").text
这个的返回值是什么

**Comment by SyuuGenn** [comment]
一个可用的代理IP，比如“171.80.162.171:42998”。我以前直接从付费代理的api接口提取ip，但是一会儿就提示一个too many open files错误。我自己建了一个代理提取接口后，跑了一会就跳上面描述的错误。

**Comment by nghuyong** [comment]
这里的代码没有问题，可能是代理质量的问题，使得网络连接出错了。

**Comment by SyuuGenn** [comment]
应该不是代理质量问题，因为一开始可以正常跑好几个小时爬二十几万条，后来可能超过了一个什么系统限制（文件描述符？）就出现错误。
