### ISSUE TITLE
分布式千万级中mongodb性能插入能撑住吗？

### ISSUE THREAD

**Issue by wmy1334** [nghuyong/WeiboSpider#11]
分布式中多台主机连到一个mongodb，一天千万级的数据的话，写入的速度能够跟上吗？写入会阻塞住吗？数据量大了之后mongodb性能会下降吧。因为没有这个环境只好来提问了。

**Comment by nghuyong** [comment]
正在尝试构建分布式， 每天上亿的大规模抓取，我会更新我测试的情况。
目前来说，单机(Macbook Pro)一天千万级，IO方面没有任何问题，可能我是SSD，普通硬盘可能差一点，具体待测试

**Comment by wmy1334** [comment]
感谢大佬的回答，也就是常规爬虫，也不会对Mongodb进行优化吧，之前面试遇到面试官问<mongodb的io处理如果跟不上怎么办?>，我就在想数据达到多少才会造成这个瓶颈，感觉一般真的需要优化吗？

**Comment by nghuyong** [comment]
是，其实就是一个IO匹配的问题。至少我也还不会对mongodb底层进行优化，只能说转换成异步，或者分级别存储，比如如果数据量过大，可以先存储到redis中，再慢慢写入mongodb中
