### ISSUE TITLE
代理ip

### ISSUE THREAD

**Issue by jiongjiong-zzzzzz** [nghuyong/WeiboSpider#110]
大佬你之前写的更换代理ip，每次请求都会用一个新的ip
写成这样会不会好一点
1，使用这个ip爬取数据，如果没有被网站Ban掉就一直使用这个ip
2，如果这个ip失效了，或者是也被ban了，就在从ip接口里再获取一个ip继续请求
我仔细研究了一下，代码不知道咋写，能不能提供一下一下思路

**Comment by nghuyong** [comment]
自己维护一个ip池，ip池负责添加新的ip，定期检查ip是否可用（不可用移除），评价ip的质量（访问速度），基于访苏速度构建一个优先队列。
我写的更换代理ip，每次请求都会用一个新的ip，其实是从构建的帐号池里面去拿一个ip。

**Comment by jiongjiong-zzzzzz** [comment]
一般买的代理都有时效性，每次请求都用一个新ip的话，会不会有点浪费？如果ip没有被封，就一直用这个ip，这种思路用scrapy怎么实现？
