### ISSUE TITLE
爬取0页的问题

### ISSUE THREAD

**Issue by shanmon110** [nghuyong/WeiboSpider#111]
我在search这个分支上运行时，一开始可以爬取，后来就爬不了了，日志报这个，请问怎么回事？
INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)

**Comment by nghuyong** [comment]
有向redis注入数据吗？

**Comment by shanmon110** [comment]
注入了，账号池也注入了

**Comment by shanmon110** [comment]
我重新清理了下redis缓存，重新按照步骤来了一次，就好了

**Comment by 1747238831** [comment]
我猜是redis里面存的链接，爬了之后就会删除

**Comment by nghuyong** [comment]
对的，redis中的链接，爬了就会被删除
