### ISSUE TITLE
只爬取某一年的微博

### ISSUE THREAD

**Issue by scutHongyuLi** [nghuyong/WeiboSpider#115]
有个疑惑想请教一下您，就是如何只爬取用户某一年的全部微博， 比如说只爬取人民日报2019年发布的微博，我克隆您的代码运行的时候，我发现一开始是爬取2019年的微博，然后一段时间后突然就跳到了2012年，接着从2012年开始爬取，所以请问一下您，如果修改一下代码使得只爬取2019当年的一个数据？

**Comment by nghuyong** [comment]
https://github.com/nghuyong/WeiboSpider/blob/master/sina/spiders/weibo_spider.py#L107
修改这里，不要获取全部的页数，而是仅仅是2019的页数。具体页数是多少可以在网页上看一下。
