### ISSUE TITLE
MongoDB数据库需要自己建表吗？

### ISSUE THREAD

**Issue by WvDevin** [nghuyong/WeiboSpider#12]
MongoDB数据库需要自己建表吗？
还是直接运行python代码就行？

**Comment by nghuyong** [comment]
不需要，直接运行即可

**Comment by vinsec** [comment]
@nghuyong 爬完之后，通过shell进入到mongodb内 show dbs ， 无法找到Sina这个数据库

**Comment by nghuyong** [comment]
log中显示有数据抓取到了吗？

**Comment by vinsec** [comment]
> log中显示有数据抓取到了吗？

需通过scrapy运行，不能直接运行脚本；后者无法建库表；
已解决
