### ISSUE TITLE
运行login.py报错

### ISSUE THREAD

**Issue by xiaolinfan** [nghuyong/WeiboSpider#120]
def __init__(self, username, password):
        **_os.system('pkill -f phantomjs')_**
        print(3)
        self.url = 'https://passport.weibo.cn/signin/login?entry=mweibo&r=https://weibo.cn/'
        self.browser = webdriver.PhantomJS(executable_path=r'D:\Program Files (x86)\phantomjs-2.1.1-windows\bin\phantomjs.exe')
        self.browser.set_window_size(1050, 840)
        self.wait = WebDriverWait(self.browser, 20)
        self.username = username
        self.password = password
**请问这句os.system('pkill -f phantomjs')是什么意思，运行login.py报错**
报错内容为：'pkill' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by nghuyong** [comment]
os.system('pkill -f phantomjs')
这行是杀死phantomjs程序，windows下面注释这行代码即可

**Comment by xiaolinfan** [comment]
==========zhukuangwang1981@163.com==========
zhukuangwang1981@163.com YUJoys147aN
Message: 


Process finished with exit code 0
注释掉也没有报错，但是cookie没有获取成功，也没在mongodb中加入东西，是直接运行login.py吗
