### ISSUE TITLE
运行login.py需要设置什么吗

### ISSUE THREAD

**Issue by xiaolinfan** [nghuyong/WeiboSpider#121]
==========zhukuangwang1981@163.com==========
zhukuangwang1981@163.com YUJoys147aN
Message:

Process finished with exit code 0
注释掉os.system()那行没有报错了，但是cookie没有获取成功，也没在mongodb中加入东西，是直接运行login.py吗

**Comment by nghuyong** [comment]
说明这个帐号是需要验证码的，可以在浏览器登陆看看是不是有验证码

**Comment by xiaolinfan** [comment]
是需要验证码，账号类型还不一样吗，要找那些不需要验证码的

**Comment by xiaolinfan** [comment]
请问您用的什么mongodb管理工具

**Comment by nghuyong** [comment]
推荐使用DataGrip

**Comment by xiaolinfan** [comment]
哦哦，谢谢
