### ISSUE TITLE
请问代理ip这里怎么弄

### ISSUE THREAD

**Issue by xiaolinfan** [nghuyong/WeiboSpider#124]
爬取一部分数据后，报错，ip被封了。请问代理ip那里的fetch_proxy函数该怎样解决

**Comment by gyqGitHub** [comment]
大佬，我也遇到了这个问题，请问你也解决了吗 @xiaolinfan

**Comment by nghuyong** [comment]
这个函数返回一个代理IP即可，这个代理IP你可以通过买代理IP的服务得到

**Comment by gyqGitHub** [comment]
> 这个函数返回一个代理IP即可，这个代理IP你可以通过买代理IP的服务得到

找了亿牛云，但是接入还需要输入账户密码，不知道怎么改，哪个网站可以直接给代理ip的，大佬能推荐一个吗 @ nghuyong

**Comment by nghuyong** [comment]
我用的是 快代理

**Comment by gyqGitHub** [comment]
> 我用的是 快代理

好的，谢谢，还有个问题，初始化账号的时候，获取成功了几次登陆ccokie之后就再也没成功了，message是空的，这也是ip被封导致的吗？

**Comment by gyqGitHub** [comment]
> 我用的是 快代理

谢谢！！！问题已解决

**Comment by arthur-cen** [comment]
> 我用的是 快代理

可否给个使用快代理建立IP池的代码示例？我用了他们官方的API scrapy[代码示例](https://www.kuaidaili.com/doc/dev/sdk_http/#scrapy) 但是在爬的时候总是不成功。

**Comment by sch919131030** [comment]
> > 我用的是 快代理
> 
> 谢谢！！！问题已解决

请问你是买的快代理的哪一种？是隧道代理吗？

**Comment by muyufujianxiaobawang** [comment]
请问微博关注、粉丝都只能看五页，这个这么破啊

**Comment by PeiyangTang** [comment]
> 请问微博关注、粉丝都只能看五页，这个这么破啊

你需要获得你要爬取人的授权， 拿到token，才能看到所有的关注和粉丝

**Comment by mango941231** [comment]
> 我用的是 快代理

用的哪个套餐呢 比较适合的

**Comment by arthur-cen** [comment]
> > 我用的是 快代理
> 
> 用的哪个套餐呢 比较适合的

我用了他们的隧道代理，感觉最方便。
下面是代码示例，购买后只要替换<你的用户名>和<你的密码>即可：

只要改写`middlewares.py`中的`IPProxyMiddleware` class 即可：
```javascript
class IPProxyMiddleware(object):
    def process_request(self, request, spider):
        proxy = "tps125.kdlapi.com:15818"
        request.meta['proxy'] = "http://%(proxy)s" % {'proxy': proxy}
        # 用户名密码认证
        username = <你的用户名>
        password= <你的密码>
        request.headers['Proxy-Authorization'] = basic_auth_header(username, password)  # 白名单认证可注释此行
        request.headers['Accept-Encoding']='gzip'
        return None
```

**Comment by kuaidaili-dev** [comment]
> > 我用的是 快代理
> 
> 可否给个使用快代理建立IP池的代码示例？我用了他们官方的API scrapy[代码示例](https://www.kuaidaili.com/doc/dev/sdk_http/#scrapy) 但是在爬的时候总是不成功。

您好，我们的代码样例新增了[Python-Scrapy](https://www.kuaidaili.com/doc/dev/sdk_http/#proxy_python-scrapy)的本地IP池维护，您可以参考参考。

**Comment by no1991** [comment]
> > > 我用的是 快代理
> > 
> > 
> > 用的哪个套餐呢 比较适合的
> 
> 我用了他们的隧道代理，感觉最方便。 下面是代码示例，购买后只要替换<你的用户名>和<你的密码>即可：
> 
> 只要改写`middlewares.py`中的`IPProxyMiddleware` class 即可：
> 
> ```python
> class IPProxyMiddleware(object):
>     def process_request(self, request, spider):
>         proxy = "tps125.kdlapi.com:15818"
>         request.meta['proxy'] = "http://%(proxy)s" % {'proxy': proxy}
>         # 用户名密码认证
>         username = <你的用户名>
>         password= <你的密码>
>         request.headers['Proxy-Authorization'] = basic_auth_header(username, password)  # 白名单认证可注释此行
>         request.headers['Accept-Encoding']='gzip'
>         return None
> ```


请问下这个
basic_auth_header，是在哪里定义的

**Comment by Ttttzc** [comment]
> 隧道代理
请问现在隧道代理还适用吗？

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦

**Comment by Huangliming0205** [comment]
cookie被封有什么好的解决办法吗

**Comment by nghuyong** [comment]
换个cookie～

**Comment by ljw0602** [comment]
请问现在怎么使用代理呢？

**Comment by pyvadev** [comment]
@ljw0602  [HttpProxyMiddleware](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html?highlight=proxy#scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware)

**Comment by everchangingsee** [comment]
请问现在怎么使用代理呢？之前的代码还可以使用吗？
