### ISSUE TITLE
如何爬取具体时间段的微博内容

### ISSUE THREAD

**Issue by onion-lbx** [nghuyong/WeiboSpider#131]
我是一个初学者，您的代码写的非常好，非常感谢您的帮助。如果提的问题让您见笑了，还请多多包涵。

其实我看到有其他人提问了如果固定爬取某一账号某一年的微博。您给出的解决方案我看了，更改此行代码**all_page = re.search(r'/>&nbsp;1/(\d+)页</div>', response.text)**，2019年的具体页数自己可以在网页上看。

我的问题是，我想从现在往回爬到2020年1月1日，2020年1月1日的微博在weibo.cn中页数是307页（也就是说页数跨度是1-307页），我将代码更改为**all_page = re.search(r'/>&nbsp;307/(\d+)页</div>', response.text)**，最后发现不能实现自己的需求。是我改错了代码吗？如果方便的话，是否可以请您指教此条代码如何修改，才能实现需求。

让您费心阅读了，新手上路总是想把所有的事情讲出来，字数冗长，还请您多多包涵。

**Comment by onion-lbx** [comment]
不好意思，还想问，如果具体想爬取70——307页的微博，应该如何修改？

 if response.url.endswith('page=70'):
            # 如果是第70页，一次性获取后面的所有页
            all_page = re.search(r'/>&nbsp;307/(\d+)页</div>', response.text)

是上面这样的吗？麻烦您了

**Comment by nghuyong** [comment]
最好的方法是，不要一次性获取全部的页数，
而是一页页的爬，然后判断一下采集微博的时间是不是在所设定的时间范围内，
如果不再，就停止往后继续翻页了

**Comment by onion-lbx** [comment]
我今天尝试了一下，按照页数爬（如果代码我改对了的话）：

if response.url.endswith('page=307'):
# 如果是第70页，一次性获取后面的所有页
all_page = re.search(r'/> 308/(\d+)页', response.text)

但是采集到的微博的时间依旧是今天的，而不是网页上307页上2020年1月的微博

我有些愚钝，不好意思啊，请问该如何解决？（对了，我运行的是simple的单个账号版本）

**Comment by onion-lbx** [comment]
我今天尝试了一下，按照页数爬（如果代码我改对了的话）：

if response.url.endswith('page=307'):
如果是第70页，一次性获取后面的所有页
all_page = re.search(r'/> 308/(\d+)页', response.text)

但是采集到的微博的时间依旧是今天的，而不是网页上307页上2020年1月的微博

我有些愚钝，不好意思啊，请问该如何解决？（对了，我运行的是simple的单个账号版本）

**Comment by nghuyong** [comment]
指定的一个用户，比如用户id为7323591999
可以通过下面这个链接搜索该用户在指定时间包含指定关键词的微博
https://weibo.cn/7323591999/search?f=u&rl=0
但是，如何获得全量微博呢？
实际上是没有办法的，因为关键词这项是必填的，但是可以曲线一下：
指定关键词为： 。.？！
