### ISSUE TITLE
请教一下爬出来的数据是存在哪里了？

### ISSUE THREAD

**Issue by wayzlin** [nghuyong/WeiboSpider#134]
![QQ截图20200308155230](https://user-images.githubusercontent.com/32737447/76158832-19221580-6155-11ea-9028-1482b822028f.png)

爬完之后是这样的。然后打开MongoDB可以看到Sina数据库，但是里面什么也没有，请问数据是存在哪里？

**Comment by nghuyong** [comment]
数据存储在mongodb中
