### ISSUE TITLE
初始化redits之后，account中的status从success变为error

### ISSUE THREAD

**Issue by sch919131030** [nghuyong/WeiboSpider#135]
因为买不到无验证的小号，所以使用的是有验证的小号，并手动在数据库中创建了account表，存入了cookie。然后初始化redits后，发现status从success变为error。然后再次手动将表中的status全部改为success，发现可以抓取到一个用户的information，但是接下来account表的status再次变为error，导致账号池为空。请问问题出在哪呢？谢谢

**Comment by sch919131030** [comment]
我输出http_code看了一下，并不是cookie失效或者账号被封的问题，请问有什么解决办法吗，因为真的买不到无验证的小号

**Comment by wula1** [comment]
@sch919131030 请问这个问题你解决了吗？我也有这个苦恼，到处都找不到免验证的小号。对此很发愁。

**Comment by Yao0420** [comment]
@sch919131030 
请问您解决了么  我也碰到这个问题  求指点

**Comment by 08163182** [comment]
> @sch919131030
> 请问您解决了么 我也碰到这个问题 求指点

 = =。现在解决了吗？老哥，求指点
