### ISSUE TITLE
终端卡顿后刷新redis，提示帐号池为空

### ISSUE THREAD

**Issue by 2shuu** [nghuyong/WeiboSpider#137]
使用cookies登录，正常运行，之后出现连续10几分钟的scrapy.extensions.logstats提示，无法爬取新数据
![image](https://user-images.githubusercontent.com/27876869/77846631-fc27b200-71e9-11ea-925f-2d5db69bf236.png)
刷新redis缓存

刷新成功，提示有新的request，但提示账号池为空，仍然无法爬取新数据（但实测账号仍可登录）
![image](https://user-images.githubusercontent.com/27876869/77846678-4d37a600-71ea-11ea-8042-7b520813ef90.png)
请问是因为现在的小号需要验证码的原因吗？

**Comment by nghuyong** [comment]
账号池中的账号的状态已经变成了error了，所以无可用账号了
