### ISSUE TITLE
微博免验证码小号购买途径[实时更新]

### ISSUE THREAD

**Issue by nghuyong** [nghuyong/WeiboSpider#139]
该Issue区将实时讨论免验证码的微博小号购买途径

![image](https://user-images.githubusercontent.com/16462374/79357843-1ea02600-7f73-11ea-9f93-38c3c0b2adcf.png)

**Comment by tlemar** [comment]
帮贴个链接

**Comment by Fyzjym** [comment]
图中联系方式均无人回应，方便的话能给web链接吗。十分感谢

**Comment by tlemar** [comment]
链接找到了， https://www.58jisu.com/PwkYxi

**Comment by eXun-Ma** [comment]
给的链接现在也不卖免验小号了QAQ

**Comment by arsMarvin** [comment]
所以大家有购买免验小号的渠道么？

**Comment by shimachao** [comment]
我就去年买的10个便宜的小号用到现在，不过我的频率不高，一个小时爬一次

**Comment by iamweizhi** [comment]
上面小号链接还能用吗

**Comment by shimachao** [comment]
尼玛，现在都需要验证了

**Comment by shimachao** [comment]
还有谁知道其他的购买渠道吗

**Comment by shimachao** [comment]
> 链接找到了， https://www.58jisu.com/PwkYxi

这买到的，不管什么价位，不是要手机号验证就是要邮件验证

**Comment by yangjinzeMR** [comment]
你们现在怎么购买微博不要验证的
小号的

**Comment by codekongs** [comment]
为什么现在的账号都需要手机验证

**Comment by carto-zed** [comment]
我去年买的一百个免验号，现在都要验证手机了

**Comment by gitjk53** [comment]
所以只能自己开小号了么？爬到什么程度会被微博封号啊？

**Comment by goodtalen** [comment]
> 该Issue区将实时讨论免验证码的微博小号购买途径
> 
> ![image](https://user-images.githubusercontent.com/16462374/79357843-1ea02600-7f73-11ea-9f93-38c3c0b2adcf.png)

不能用呀，买了白买，买了个寂寞

**Comment by Les1ie** [comment]
可以通过手机上微博极速版或者国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie

**Comment by zhunipingan** [comment]
有知道可以买豆瓣小号的方法吗

**Comment by banyiluoyun** [comment]
> 可以通过手机上微博极速版或者国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie

刚刚下载测试了，并不行，登录验证体系是同一个。此路不通，建议换条路

**Comment by Les1ie** [comment]
> > 可以通过手机上微博极速版或国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie
> 
> 刚刚下载测试了，并不行，登录验证体系是同一个。此路不通，建议换条路

你用是国际版吗？我用极速版可以呀

**Comment by Les1ie** [comment]
选择“使用其他方式验证”，然后使用微博极速版APP登陆后接受私信验证码：
![image](https://user-images.githubusercontent.com/28597662/99933875-37897900-2d97-11eb-9c2d-20cd157ee2ac.png)
要是没有“使用其他方式验证”这个选项可能是买的账号有问题……

**Comment by banyiluoyun** [comment]
> > > 可以通过手机上微博极速版或国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie
> > 
> > 
> > 刚刚下载测试了，并不行，登录验证体系是同一个。此路不通，建议换条路
> 
> 你用是国际版吗？我用极速版可以呀
> ![Screenshot_20201123_134448_com sina weibolite](https://user-images.githubusercontent.com/28597662/99932261-7ff26800-2d92-11eb-865c-62c1384fc962.jpg)

极速版国际版我都测试了，账号在极速版或者国际版登录的时候会被短信验证。。。登录不上app，更谈不上通过私信验证登录网页版了

**Comment by Les1ie** [comment]
那应该是你的账号问题哦，我刚刚买了一个号极速版app都可以登录


 
---原始邮件---
发件人: "banyiluoyun"<notifications@github.com&gt;
发送时间: 2020年11月23日(星期一) 下午2:28
收件人: "nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Leslie"<498721344@qq.com&gt;;
主题: Re: [nghuyong/WeiboSpider] 微博免验证码小号购买途径[实时更新] (#139)




    
可以通过手机上微博极速版或国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie
  
刚刚下载测试了，并不行，登录验证体系是同一个。此路不通，建议换条路
  
你用是国际版吗？我用极速版可以呀
 
  
极速版国际版我都测试了，账号在极速版或者国际版登录的时候会被短信验证。。。登录不上app，更谈不上通过私信验证登录网页版了

**Comment by banyiluoyun** [comment]
> 那应该是你的账号问题哦，我刚刚买了一个号极速版app都可以登录
> […](#)
> ---原始邮件--- 发件人: "banyiluoyun"<notifications@github.com&gt; 发送时间: 2020年11月23日(星期一) 下午2:28 收件人: "nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Leslie"<498721344@qq.com&gt;; 主题: Re: [nghuyong/WeiboSpider] 微博免验证码小号购买途径[实时更新] (#139) 可以通过手机上微博极速版或国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie 刚刚下载测试了，并不行，登录验证体系是同一个。此路不通，建议换条路 你用是国际版吗？我用极速版可以呀 极速版国际版我都测试了，账号在极速版或者国际版登录的时候会被短信验证。。。登录不上app，更谈不上通过私信验证登录网页版了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我也重新买了一下5元的账号，测试了也不行。。。你买的是哪一个？

**Comment by Les1ie** [comment]
> > 那应该是你的账号问题哦，我刚刚买了一个号极速版app都可以登录
> > […](#)
> > ---原始邮件--- 发件人: "banyiluoyun"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年11月23日(星期一) 下午2:28 收件人: "nghuyong/WeiboSpider"<[WeiboSpider@noreply.github.com](mailto:WeiboSpider@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"Leslie"<[498721344@qq.com](mailto:498721344@qq.com)>; 主题: Re: [nghuyong/WeiboSpider] 微博免验证码小号购买途径[实时更新] (#139) 可以通过手机上微博极速版或国际版登陆这些账号，这些APP上不需要验证，通过APP内的消息接受验证码，然后再网页登陆，保存Cookie 刚刚下载测试了，并不行，登录验证体系是同一个。此路不通，建议换条路 你用是国际版吗？我用极速版可以呀 极速版国际版我都测试了，账号在极速版或者国际版登录的时候会被短信验证。。。登录不上app，更谈不上通过私信验证登录网页版了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我也重新买了一下5元的账号，测试了也不行。。。你买的是哪一个？

你试试这个 http://weihaizhuan.com/trade/3.html 多买几个，有些是可以的。前几天我试了，不能保证百分百全部能登陆，但是有些可以

**Comment by Xandra298** [comment]
现在微博都不能免验了吧？

**Comment by nghuyong** [comment]
@Xandra298 对的，微博现在网页版本都不能免验证码了

**Comment by Xandra298** [comment]
那么现在还有没有什么办法可以进行模拟登录

**Comment by nghuyong** [comment]
@Les1ie @Xandra298 @banyiluoyun 同步一下，目前微博的国际版和极速版不支持免验证码登陆了，需要手机短信验证码登陆。目前来看暂时不能自动构建账号池了。欢迎继续交流讨论。

**Comment by Boobh** [comment]
cookie替换后还需要处理吗  为什么分布式的我连自己的号都用不了

**Comment by Boobh** [comment]
cookie替换后还需要处理吗  为什么分布式的我连自己的号都用不了

**Comment by nghuyong** [comment]
@Boobh 不需要处理，请先确认可以在单机版的环境中跑通整个流程

**Comment by Boobh** [comment]
COV数据集申请一般需要申请多久才能通过

**Comment by nghuyong** [comment]
@Boobh 一般情况下收到后当天就会回复或者通过，您的邮件可能被拦截了，辛苦再发送一次

**Comment by Boobh** [comment]
> @Boobh 一般情况下收到后当天就会回复或者通过，您的邮件可能被拦截了，辛苦再发送一次

我把章补上了  麻烦看一下那样可以吗

**Comment by banyiluoyun** [comment]
> @Les1ie @Xandra298 @banyiluoyun 同步一下，目前微博的国际版和极速版不支持免验证码登陆了，需要手机短信验证码登陆。目前来看暂时不能自动构建账号池了。欢迎继续交流讨论。

找其他的接口抓取吧，我目前走的是微博的微信小程序抓取，不需要登录，也可抓取大批量的评论和微博信息

**Comment by BestLemoon** [comment]
> > @Les1ie @Xandra298 @banyiluoyun 同步一下，目前微博的国际版和极速版不支持免验证码登陆了，需要手机短信验证码登陆。目前来看暂时不能自动构建账号池了。欢迎继续交流讨论。
> 
> 找其他的接口抓取吧，我目前走的是微博的微信小程序抓取，不需要登录，也可抓取大批量的评论和微博信息

可以讲讲详细方法吗，谢谢！

**Comment by banyiluoyun** [comment]
@BestLemoon 就抓包过滤，模拟请求，完事。抓小程序那一套呗，有啥好讲的

**Comment by Kelaxon** [comment]
@banyiluoyun 并不能获取大量评论吧？我刚测了一下这种方式对于一条微博下的评论也最多只能获取几百条。
> 找其他的接口抓取吧，我目前走的是微博的微信小程序抓取，不需要登录，也可抓取大批量的评论和微博信息

**Comment by a518518-ui** [comment]
> 套

怎么抓包，可以发下大神你qq吗 有事请教

**Comment by wbloc** [comment]
有谁知道免验证的小号购买渠道吗

**Comment by wbloc** [comment]
有谁知道免验证的小号购买渠道吗

**Comment by nghuyong** [comment]
目前微博已经很难通过小号进行免验证码登陆了，该issue就此关闭

**Comment by Les1ie** [comment]
wz已收到您的邮件

**Comment by rich168** [comment]
根本不行了

**Comment by popecat** [comment]
推荐的那个网站已经挂了

**Comment by Les1ie** [comment]
wz已收到您的邮件

**Comment by nghuyong** [comment]
目前微博已经不能通过小号进行免验证码登陆了，该issue关闭

**Comment by liuliang520530** [comment]
地址奉上：bbs.weiququ.cn

**Comment by Les1ie** [comment]
wz已收到您的邮件。

**Comment by Aszalea** [comment]
现在有新的网址吗？

**Comment by Les1ie** [comment]
wz已收到您的邮件。

**Comment by fenglander** [comment]
地址访问不了，还有途径吗

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦
