### ISSUE TITLE
暂停爬虫 怎么避免重复爬取

### ISSUE THREAD

**Issue by Verasince1997** [nghuyong/WeiboSpider#143]
本程序没有这个功能哇
思路是设置缓存池 爬之前先访问缓存池 如果没有 再爬 
说起很抽象 我想办法去搜搜教程 试试可以不

**Comment by nghuyong** [comment]
可以设计，需要额外记录爬虫抓取的网页状态
更多设计可以参考这里:
https://www.zhihu.com/question/29754961

**Comment by kingking888** [comment]
Redis说：I'm so lonely
