### ISSUE TITLE
关于docker stack

### ISSUE THREAD

**Issue by yuanzhouIR** [nghuyong/WeiboSpider#146]
请教一下，docker stack应该怎么用，可以写得具体一些吗？为什么不用docker compose?

**Comment by nghuyong** [comment]
docker swarm 对分布式的支持更好一点
更多：https://linuxhint.com/docker_compose_vs_docker_swarm/

**Comment by yuanzhouIR** [comment]
> docker swarm 对分布式的支持更好一点
> 更多：https://linuxhint.com/docker_compose_vs_docker_swarm/

感谢回复！那请问是不是我只开一个爬虫的话用docker compose就可以？

**Comment by nghuyong** [comment]
对的，可以

**Comment by yuanzhouIR** [comment]
> 对的，可以

不好意思，继续请教一下，我用docker swarm创建了一个集群（一个manager一个worker），然后执行docker stack deploy -c docker-compose.yml weibospider成功了。但是portainer打不开，http://127.0.0.1:7000无法访问。docker service ls看了一下，REPLICAS除了mongo-express是1/1，其他都是0/1（如下图）。能请问一下这是怎么回事吗？
<img width="1240" alt="スクリーンショット 2020-04-22 19 07 31" src="https://user-images.githubusercontent.com/35292602/79970007-3cb6da80-84cd-11ea-8fc9-4dc08b1f47c9.png">

**Comment by nghuyong** [comment]
docker service logs weibospider_mongdb

**Comment by yuanzhouIR** [comment]
> 1. 确定一下是不是镜像都有了
>    docker images
> 2. 查看日志 docker service logs 
>    比如： docker service logs weibospider_mongdb

镜像都有了，查看日志时发现portainer服务有一个invalid argument（如下图）。
<img width="878" alt="スクリーンショット 2020-04-22 20 08 51" src="https://user-images.githubusercontent.com/35292602/79975223-97eccb00-84d5-11ea-9f1e-9c93479b1123.png">

mongodb服务的日志如下：

>weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.805+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.808+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.808+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=96673a722390
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] db version v4.2.6
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] modules: none
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] build environment:
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten]     distarch: x86_64
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.809+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.810+0000 I  STORAGE  [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.810+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.810+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.810+0000 I  CONTROL  [initandlisten] now exiting
weibospider_mongodb.1.gxf6zblnd1y3@manager1    | 2020-04-22T11:10:48.810+0000 I  CONTROL  [initandlisten] shutting down with code:100
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.510+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.515+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=6b7663bab658
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] db version v4.2.6
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] modules: none
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] build environment:
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten]     distarch: x86_64
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.516+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.517+0000 I  STORAGE  [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.519+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.519+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.519+0000 I  CONTROL  [initandlisten] now exiting
weibospider_mongodb.1.uho7pu6tnnco@worker1    | 2020-04-22T11:10:54.519+0000 I  CONTROL  [initandlisten] shutting down with code:100
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.212+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=7dbbb0c40ab9
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] db version v4.2.6
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] modules: none
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] build environment:
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten]     distarch: x86_64
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.215+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.217+0000 I  STORAGE  [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.217+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.217+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.218+0000 I  CONTROL  [initandlisten] now exiting
weibospider_mongodb.1.bnd9fvluau2h@worker1    | 2020-04-22T11:10:43.218+0000 I  CONTROL  [initandlisten] shutting down with code:100
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.058+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.060+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.061+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=24dda3b4a58b
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.061+0000 I  CONTROL  [initandlisten] db version v4.2.6
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten] git version: 20364840b8f1af16917e4c23c1b5f5efd8b352f8
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten] modules: none
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten] build environment:
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten]     distarch: x86_64
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.062+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.063+0000 I  STORAGE  [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.063+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.063+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.063+0000 I  CONTROL  [initandlisten] now exiting
weibospider_mongodb.1.9esr26gs169u@worker2    | 2020-04-22T11:11:00.063+0000 I  CONTROL  [initandlisten] shutting down with code:100

我用的macbook，yaml文件就是完全复制了你的内容，是不是因为yaml文件的原因？

**Comment by nghuyong** [comment]
STORAGE [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
./data/mongo 目录加一个写入权限

**Comment by yuanzhouIR** [comment]
> STORAGE [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
> ./data/mongo 目录加一个写入权限

是因为数据要保存到本地所以需要获取./data/mongo目录权限吗？具体应该怎么操作？

**Comment by yuanzhouIR** [comment]
> STORAGE [initandlisten] exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating
> ./data/mongo 目录加一个写入权限

知道原因了，Windows和OS X不支持挂载主机目录。https://registry.hub.docker.com/_/mongo/
WARNING (Windows & OS X): The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see vbox bug, docs.mongodb.org and related jira.mongodb.org bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.
