### ISSUE TITLE
字段疑问

### ISSUE THREAD

**Issue by BasicCoder** [nghuyong/WeiboSpider#147]
请问一下，转发的博文中“origin_weibo”字段表示的是被转发微博的url，那这个url的格式怎么和“weibo_url”字段不一样呢？  就是说我想根据爬取到的博文数据，找出博文之间的转发关系，但是对爬取到的数据查看发现，那些有“origin_weibo”字段的博文，“origin_weibo”字段值在博文数据中都不存在。也就是无法建立转发关系。

**Comment by nghuyong** [comment]
origin_weibo URL 的格式：https://weibo.cn/comment/ImGgq3tG2
最后的ImGgq3tG2也就是origin_weibo的_id

**Comment by BasicCoder** [comment]
我爬取的数据中有：
"origin_weibo" ： "https://weibo.cn/comment/Fhgu7jfJb?rl=1#cmtfrm"
那么origin_weibo 的 _id 应该是 "Fhgu7jfJb"
但我用  db.getCollection('Tweets').find({ "_id": /Fhgu7jfJb/ }) 这条语句查询时，发现查询结果为空。

进而我跑了全量数据，发现查询结果都是空。 是我理解错您的意思 还是 没抓取到呢？ 感谢回复！

**Comment by nghuyong** [comment]
不会自动抓取origin_weibo的数据，如果需要可以自行抓取

**Comment by BasicCoder** [comment]
好的，多谢解释！
