### ISSUE TITLE
Instructions of README.md in simple branch

### ISSUE THREAD

**Issue by AtlasChuen** [nghuyong/WeiboSpider#150]
In README.md in simple branch:
```
git clone git@github.com:nghuyong/WeiboSpider.git --depth 1
cd WeiboSpider
git checkout simple
pip install -r requirements.txt
```
Problem1:
``git clone git@github.com:nghuyong/WeiboSpider.git --depth 1``
should be:
``git clone git@github.com:nghuyong/WeiboSpider.git --depth 1 --no-single-branch``

Problem2:
no requirements.txt in repo

**Comment by nghuyong** [comment]
Fix Now, Thanks~
