### ISSUE TITLE
在执行run_spider.py时遇到的错误:    

### ISSUE THREAD

**Issue by pp0229** [nghuyong/WeiboSpider#153]
mode = sys.argv[1]
IndexError: list index out of range

**Comment by Tomhardy22** [comment]
这个咋解决

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦

**Comment by nghuyong** [comment]
参考readme，不能直接执行 `python run_spider.py` 需要跟上task的名字 例如 `python run_spider.py user`
