### ISSUE TITLE
weibo.cn不会显示50页以后的评论

### ISSUE THREAD

**Issue by shirok1** [nghuyong/WeiboSpider#157]
导致大量的时间被浪费在下载空页面上
![image](https://user-images.githubusercontent.com/12044683/83643211-56763200-a5e2-11ea-9451-e6a445b7bcbb.png)
![image](https://user-images.githubusercontent.com/12044683/83643266-6726a800-a5e2-11ea-9a6e-a7ea6dd24def.png)
实际上只需要对代码作一处修改
`all_page = all_page if all_page <= 50 else 50`
![image](https://user-images.githubusercontent.com/12044683/83643432-976e4680-a5e2-11ea-8bec-59e24fbe8b24.png)

**Comment by nghuyong** [comment]
OKO
