### ISSUE TITLE
建议更换爬取评论用的url

### ISSUE THREAD

**Issue by shirok1** [nghuyong/WeiboSpider#158]
目前的脚本爬取到的评论，除了两条热门赞数基本都是0。。
![image](https://user-images.githubusercontent.com/12044683/84593734-323b1080-ae80-11ea-933b-b60686024d55.png)
刚刚看了才知道weibo.cn其实专门有一个按赞数排名的网址（就是从那个“查看更多热门>>”点进去
`https://weibo.cn/comment/Iurl64atK?`
![image](https://user-images.githubusercontent.com/12044683/84593637-bccf4000-ae7f-11ea-9492-fba20117af2d.png)
`https://weibo.cn/comment/hot/Iurl64atK?rl=1`
![image](https://user-images.githubusercontent.com/12044683/84593647-ca84c580-ae7f-11ea-8058-5fa11317358c.png)
真的是要吐了，计划把人日的微博从五月底到元旦的微博的评论全部爬下来，现在已经爬到2月中了，结果现在来整这么一手

**Comment by nghuyong** [comment]
感谢你的建议，已经更新～
