### ISSUE TITLE
通过关键词抓取指定用户的微博？

### ISSUE THREAD

**Issue by ZhiliWang** [nghuyong/WeiboSpider#159]
你好，这真是个优秀的项目。我想通过学习你的代码来增强自己对python和爬虫的认识，想请问下，你的“抓取包含关键词的微博”是指对用户无差别，并抓取指定时间段内的微博吗？有没有可能在关键词+时间的基础上再指定某个/某些群体的用户呢？谢谢！

**Comment by nghuyong** [comment]
可以实现对于**指定用户**，**指定关键词**，**指定时间段**的微博
https://weibo.cn/search/mblog?advanced=mblog&f=s
![image](https://user-images.githubusercontent.com/16462374/85240649-78d5cf80-b46b-11ea-8ee0-4de7b191bf59.png)

**Comment by ZhiliWang** [comment]
抱歉，我基本功太差了，研究了很长时间，但还是不知道怎么通过修改你的代码来在本地实现这个功能，能请你给点提示吗？

**Comment by nghuyong** [comment]
https://github.com/nghuyong/WeiboSpider/blob/simple/weibospider/spiders/tweet.py#L38

**Comment by ZhiliWang** [comment]
感谢回复！抱歉我之前没把问题说清楚，请问这个URL要怎么把指定用户加到39行的advancedfilter里？我试过u, uid, id, username，userid, user_id之类的，都不行，例如：
https://weibo.cn/search/mblog?hideSearchFrame=&keyword=例子&advancedfilter=1&user_id=6340375022&starttime=2017-07-30&endtime=2017-08-30&sort=time&page=1

我用了你第一次回答我的高级搜索搜完，也不会显示出完整的URL，只会显示“https://weibo.cn/search/”

难道真的只能强行搜所有这个用户在一个时间段内发得所有微博，再逐个看是否包含关键字？

**Comment by nghuyong** [comment]
点击下一页URL就有了，第一页没有

**Comment by ZhiliWang** [comment]
完全明白了，因为我之前搜的主题内容比较冷门，之前连一页都搜不满。作者非常有耐心，并完美得回答了我的所有问题，感谢！
