### ISSUE TITLE
[探讨]有没有办法能大批量通过昵称获得数字型uid

### ISSUE THREAD

**Issue by ZhiliWang** [nghuyong/WeiboSpider#160]
你好，我想给这个项目写一个辅助性的，将大量昵称转为数字型UID的程序，然后对接这个项目里任何要用到数字型uid搜索功能。比方说，我想增强抓取数据的权威性，先搜出一大批包含”新闻“，”官方“，”权威“的用户名，用某种方法把这批用户名换成数字型UID，再接上你的项目来通过用户名+关键词+时间来搜twits

我写了个程序可以通过pc端的搜索url来达到这个目的（我可以分享我的代码）:
"https://s.weibo.com/user/&nickname={}&page={}".format(urllib.parse.quote(userName),  1)

但是问题在于，如果目标用户已经给账户改了char型的UID得话，没法得到数字型UID。 但是如果用移动端的搜索URL的话没法抓取：'https://weibo.cn/search/user/?keyword={}&page={}'.format(quote(userName), 1)。我觉得数字型的ID对

我另一个想法是，能不能直接通过 'https://weibo.cn/search/user/?keyword=[用户名中包含的关键词]&page=1' 抓取我需要的用户名单时直接通过某种方式得到数字型的UID？

请问你觉得只用移动端的url抓取得话，理论上能实现吗？你之前有这方面的想法吗？

**Comment by nghuyong** [comment]
https://github.com/nghuyong/weibo-public-opinion-datasets
可以参考这个项目，通过种子用户+社交网络扩列，理论上你可以把微博全部用户信息爬下来，我已经构建了约3亿的用户池了，然后导入ES，就可以全文检索昵称了.
