### ISSUE TITLE
评论爬了几百条之后，提示“还没有人针对这条微博发表评论!”

### ISSUE THREAD

**Issue by sshimii** [nghuyong/WeiboSpider#164]

**Comment by nghuyong** [comment]
@sshimii 有具体的例子吗，针对的哪一条微博

**Comment by sshimii** [comment]
![image](https://user-images.githubusercontent.com/41730403/88500787-47b56580-cffc-11ea-8f29-4ace0c6772c2.png)
redis_init文件里面这个函数
def init_comment_spider():
    # change the tweet ids
    tweet_ids = ['IDl56i8av', 'IDkNerVCG', 'IDkJ83QaY']
    urls = [f"https://weibo.cn/comment/hot/{tweet_id}?rl=1&page=1" for tweet_id in tweet_ids]
    redis_init('comment_spider', urls)

在爬微博的时候，url如果加了hot，比如这条微博：IDl56i8av，共有112页评论，但是点到三十几页内容就不更新了，112页，50页和40页的内容是一样的。
如果去掉'/hot'，评论会多一点，但是50页之后，比如输入51页，跳转之后就会显示‘还没有人针对这条微博发表评论!’

**Comment by nghuyong** [comment]
对的，这个是微博本身的限制，不能获取全量的评论。
建议添加/hot，这样可以率先获得热门的评论
