### ISSUE TITLE
有关登录Cookie存活时间和爬取间隔的问题

### ISSUE THREAD

**Issue by leyuwei** [nghuyong/WeiboSpider#168]
最近有一个简单项目需求，服务器环境有限，所以额外给Simple分支加了CSV方式存储，没有用提供的MONGODB。
想问下在setting.py中设置爬取间隔和并发数多少较为合适？因为是第一次爬取微博数据，有点担心爬取时间过长导致ip被ban，从而数据尽失的情况（目前设置的是8并发数，8秒间隔）。此外，每一次登录后的Cookie最长存活时间是多久？望解答，感谢~

**Comment by leyuwei** [comment]
b.t.w. 感谢一下这个项目，简化了我很多的工作。。目前除了本issue提出的疑虑外，我额外加了配合Selenium的Cookie自获取，CSV存储、Tweet的大V认证与会员识别、Followers的爬取上限扩充，都工作的挺好。
额外提一个问题，tweet关键词+固定时段爬取好像会有较多重复，我目前的解决办法是增加一个字段（_id+keyword），然后EXCEL来去重，是否有更好的运行时去重方法？
额外提一个bug？tweet.py中关键词爬取函数，双重循环会导致跳页，不知是否有意为之？。我目前改为了：
```
for keyword in keywords:
                date_start = datetime.datetime.strptime(ts, '%Y-%m-%d')
                while date_start < date_end:
                    next_time = date_start + time_spread
                    url = url_format.format(keyword, date_start.strftime("%Y%m%d"), next_time.strftime("%Y%m%d"))
                    urls.append(url)
                    date_start = next_time
```

**Comment by nghuyong** [comment]
1. 采取默认simple分支的配置即可
2. 一般cookie有效期大于1个月
3.双重循环会导致跳页 这是什么意思？

**Comment by leyuwei** [comment]
> 1. 采取默认simple分支的配置即可
> 2. 一般cookie有效期大于1个月
>    3.双重循环会导致跳页 这是什么意思？

感谢您的回复，
目前抓取状态良好，部署的爬虫已经五六天连续工作正常了。
有关第三个问题，tweet.py中的init_url_by_keywords() 函数，是按`一天`切分给定检索时间段的，在您现在提供的版本中：
```
while date_start < date_end:
    for keyword in keywords:
        next_time = date_start + time_spread
        url = url_format.format(keyword, date_start.strftime("%Y%m%d"), next_time.strftime("%Y%m%d"))
        urls.append(url)
        date_start = next_time
```
假设我现在检索3个关键词，最后录入的就是 [关键词1 时间点1] [关键词2 时间点2] [关键词3 时间点3]  [关键词1 时间点4] [关键词2 时间点5] [关键词3 时间点6] 
单看关键词就是跳2天录一天，会有信息损失，不知现在这份代码是否是有意这样设计？

**Comment by nghuyong** [comment]
@arthur-cen 并非有意设计，单纯的写错了代码[捂脸]，已经更新啦～感谢指正！

**Comment by arthur-cen** [comment]
@nghuyong 大神圈错人了 😂, 功劳给 @leyuwei

**Comment by shimachao** [comment]
能问一下你们的微博账号从哪买的吗

**Comment by leyuwei** [comment]
> 能问一下你们的微博账号从哪买的吗

小规模需求的话，借了身边朋友的账号，开了N台树莓派，分别挂着N个代理，一起跑。。
