### ISSUE TITLE
如何根据用户id爬取某一段时间间隔内的微博？

### ISSUE THREAD

**Issue by SYChen123** [nghuyong/WeiboSpider#169]
最近的项目需要根据用户的id爬取某个时间段内用户发的微博。我想的是在parse函数里加上对created_time的限制，但是不知道该怎么加。望解答，感谢！

**Comment by nghuyong** [comment]
![image](https://user-images.githubusercontent.com/16462374/89148891-adba6380-d58d-11ea-83b0-026162fb5d87.png)
weibo.cn支持对于单个用户在某个时间段的检索，但是必须填写关键词

**Comment by SYChen123** [comment]
> ![image](https://user-images.githubusercontent.com/16462374/89148891-adba6380-d58d-11ea-83b0-026162fb5d87.png)
> weibo.cn支持对于单个用户在某个时间段的检索，但是必须填写关键词

好的，明白了，感谢！
