### ISSUE TITLE
微博登录会出现手机验证

### ISSUE THREAD

**Issue by TT9826** [nghuyong/WeiboSpider#170]
现在使用模拟浏览器登录会出现手机验证，麻烦维护一下

**Comment by nghuyong** [comment]
账号问题，请购买不需要验证码的小号；或者采用simple分支中的手工获取cookie

**Comment by TT9826** [comment]
好像是改版了吧，我的账号就是免验证账号，只是最近出现的需要其他手机发送短信登录。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nghuyong/WeiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 下午4:34
收件人:&nbsp;"nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"305396039"<305396039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nghuyong/WeiboSpider] 微博登录会出现手机验证 (#170)





 
账号问题，请购买不需要验证码的小号；或者采用simple分支中的手工获取cookie

**Comment by shimachao** [comment]
可惜买不到不需要验证码的小号，太难了

**Comment by TT9826** [comment]
现在是手机app端不需要验证，极速版微博可以抓包。
网页端的https://login.sina.com.cn/signup/signin.php?entry=blog&amp;登录需要验证码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nghuyong/WeiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 上午9:42
收件人:&nbsp;"nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"305396039"<305396039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nghuyong/WeiboSpider] 微博登录会出现手机验证 (#170)





 
可惜买不到不需要验证码的小号，太难了
