### ISSUE TITLE
小小白问两个问题..

### ISSUE THREAD

**Issue by sean-zhuh** [nghuyong/WeiboSpider#175]
1）cookie换成自己的以后python run_spider.py user后显示的是人民日报和明星，请问是哪里操作有问题？
2）抓取的数据保存在哪里？我是用的simple版
希望大佬解答..

**Comment by gitjk53** [comment]
1）你还要去spiders文件夹里头，修改对应的user.py文件，把user_id换成你自己想要爬的user。

2）抓取的数据是输出成mongoDB的数据，你需要在自己的电脑上配置好mongoDB，然后再安装mongoexport组件导出成CSV会比较方便处理数据。
