### ISSUE TITLE
simple版无法抓取数据

### ISSUE THREAD

**Issue by sean-zhuh** [nghuyong/WeiboSpider#176]
[scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
[scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
[scrapy.core.engine] DEBUG: Crawled (302) <GET https://weibo.cn/1699432410/info> (referer: None)
[scrapy.spidermiddlewares.httperror] INFO: Ignoring response <302 https://weibo.cn/1699432410/info>: HTTP status code is not handled or not allowed

请问这是什么原因，要怎么解决？

**Comment by xiaolinfan** [comment]
cookie失效了吧

**Comment by sean-zhuh** [comment]
我重新刷新了下网页的cookie还是不行发自我的iPhone------------------ 原始邮件 ------------------发件人: xiaolinfan  <notifications@github.com>发送时间: 2020年9月23日 18:05收件人: nghuyong/WeiboSpider <WeiboSpider@noreply.github.com>抄送: Sean Zhuh <sean.zhuh@gmail.com>, Author <author@noreply.github.com>主题: 回复：[nghuyong/WeiboSpider] simple版无法抓取数据 (#176)
cookie失效了吧

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nghuyong/WeiboSpider/issues/176#issuecomment-697265850",
"url": "https://github.com/nghuyong/WeiboSpider/issues/176#issuecomment-697265850",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nghuyong** [comment]
需要更新你的cookie到setting文件中，详见simple分支的readme
