### ISSUE TITLE
simple版每天只能抓取十万左右吗

### ISSUE THREAD

**Issue by xiaolinfan** [nghuyong/WeiboSpider#177]

**Comment by nghuyong** [comment]
是十万级别，不是只能抓取十万左右
simple分支setting中的配置如下：
`CONCURRENT_REQUESTS = 16`
`DOWNLOAD_DELAY = 3`
所以一天可以抓取的网页数：16(page/s) * (24 * 60 * 60 / 3) (s) = 460,800 (pages)
如果2个网页有一条数据(比如用户信息页面),那么一天的理想抓取量就是230,400
如果1个网页有十条数据(比如用户推文页面),那么一天的理想抓取量就是4,608,000(pages)
