### ISSUE TITLE
关于simple版本多个cookie改造

### ISSUE THREAD

**Issue by Terry-Ma** [nghuyong/WeiboSpider#179]
您好～我手动获取了一些cookie，尝试在单机版本加入多cookie；我将settings.py中的header信息都删除了，然后在tweet.py中定义了headers（含user-agent）和cookies，然后每次Request都会随机选取一个dict形式的cookie传入，但是还是一直<302>，我确认我的cookie是有效的，因为在setting.py用这个cookie是可以的，目前还无法定位原因，只知道在Request处传入的cookie似乎完全没有生效，即便我硬编码了一个传入。

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'}
    cookies = {
        '_T_WM': '53311762118',
        'MLOGIN': '1',
        'SSOLoginState': '1601342576',
        'SUB': '_2A25ydvwgDeRhGeFK7FUY8S_PzjWIHXVRmIRorDV6PUJbktANLRKskW1NQuoKipKPwlVpVDZuD62syuYUpkENXSXb',
        'SUBP': '0033WrSXqPxfM725Ws9jqgMF55529P9D9W5wC2uO_vlppRk._F6f_Ebp5JpX5KzhUgL.FoMXS0M4eK20SK.2dJLoIpjLxK-L12-L1hqLxKMLB.2LB-2LxKqL1-qL12qt',
        'SUHB': '010WZvL0Xfi_zV',
        'M_WEIBOCN_PARAMS': 'lfid%3D231583%26luicode%3D20000174',
        'WEIBOCN_FROM': '1110106030'
    }

XXX

for url in urls:
            yield Request(url, callback=self.parse, cookies=self.cookies, headers=self.headers)

**Comment by nghuyong** [comment]
多cookie得话，建议直接使用master分支，并手工插入多个cookie
具体参考：https://github.com/nghuyong/WeiboSpider#%E6%9E%84%E5%BB%BA%E8%B4%A6%E5%8F%B7%E6%B1%A0

**Comment by ZhiliWang** [comment]
请问有什么有效的方法可以自动化获取cookies吗？我试了很多方法都没办法搞定那个登录后的一键点击验证
