### ISSUE TITLE
请问我抓取的comment为什么为空？代码没改过

### ISSUE THREAD

**Issue by MTforever** [nghuyong/WeiboSpider#18]
![image](https://user-images.githubusercontent.com/11135686/49334825-71956980-f61a-11e8-91f6-7a9f60508a8e.png)

**Comment by MTforever** [comment]
> 你用的是哪个分支？

我用的是search分支，然后还有个问题是information里面为什么没有user_id这一项呀，该如何将information里面的人与Tweets的发布者对应起来

**Comment by nghuyong** [comment]
information里面的_id就是user_id，具体看字段说明
