### ISSUE TITLE
您好，我对于关键字爬取的时候，仅仅只能爬取前100页的数据，然后我手动把Tweet.py下的all_page改为更大的数字，但是就请求不到该url了，请问怎么样才能爬取相关关键字的所有微博数据

### ISSUE THREAD

**Issue by lao-sheng** [nghuyong/WeiboSpider#181]
![image](https://user-images.githubusercontent.com/59272013/95668385-d53d3600-0ba5-11eb-9ede-7a60af0cf294.png)
![image](https://user-images.githubusercontent.com/59272013/95668408-3b29bd80-0ba6-11eb-9348-69e58aac78ab.png)
![Uploading image.png…]()

**Comment by nghuyong** [comment]
您好，微博对关键词抓取是有页数限制的，所以通过这种方法是不能完成对指定关键词的全量微博抓取的
有一个折中的办法，可以参见 https://github.com/nghuyong/weibo-public-opinion-datasets
