### ISSUE TITLE
运行python run_spider.py tweet的时候直接报错

### ISSUE THREAD

**Issue by dbw5718** [nghuyong/WeiboSpider#182]
`File "run_spider.py", line 21
    os.environ['SCRAPY_SETTINGS_MODULE'] = f'settings'
                                                     ^
SyntaxError: invalid syntax`

第二个问题不知道是我的git出问题了，git clone git@github.com:nghuyong/WeiboSpider.git --depth 1 --no-single-branch的时候出现`Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`，然后我更新了我的公钥，但是还是没有解决，直接git clone 是可以下载的。

**Comment by nghuyong** [comment]
请确保你使用的环境是Python3.6
