### ISSUE TITLE
User抓取更多信息

### ISSUE THREAD

**Issue by ZhiliWang** [nghuyong/WeiboSpider#183]
请问，爬虫的user功能是由于哪些方面的考量导致没有选择抓取学习和工作经历呢？我想fork然后增加这项功能，想尽量避免一些弯路，谢谢！

**Comment by nghuyong** [comment]
可以添加，只是我在编写的时候，没有遇到有用户填写了这部分信息；整体填写这两个信息的用户也非常少，所以就没有编写了

**Comment by ZhiliWang** [comment]
好谢谢！
