### ISSUE TITLE
通过weibo.cn只能获取第一页评论

### ISSUE THREAD

**Issue by TongSh** [nghuyong/WeiboSpider#185]
发现使用该脚本获取微博评论时，只能获取第一页最新的8条评论。使用代码中的URL：https://weibo.cn/comment/hot/Is9M7taaY?rl=1&page=1 在浏览器尝试时，发现浏览器点击下一页，内容不会更新。

**Comment by nghuyong** [comment]
https://weibo.cn/comment/hot/JssULFNav?rl=1&page=1
URL错误了，这是正确的URL

**Comment by TongSh** [comment]
> https://weibo.cn/comment/hot/JssULFNav?rl=1&page=1
> URL错误了，这是正确的URL

当评论页数多于50页时，使用该形式的URL也无法获取

**Comment by nghuyong** [comment]
对的，这是热门评论，是不全的

**Comment by TongSh** [comment]
> 对的，这是热门评论，是不全的

发现部分微博不提供热门评论功能（比如李文亮医生的最后一条微博的评论），因此只能按时间先后爬取。从weibo.cn只能爬取最新的50页。不知道您是否有办法爬取该微博的所有评论呢？（约100万+）   科研用途~  感谢感谢

**Comment by nghuyong** [comment]
“部分微博不提供热门评论功能”感谢提醒
“爬取该微博的所有评论呢？（约100万+） ” 这个暂时我也没有办法
