### ISSUE TITLE
大佬你好，关于微博活跃用户 池的搭建和维护大佬能分享下吗

### ISSUE THREAD

**Issue by lining4069** [nghuyong/WeiboSpider#189]
大佬你好，我是计算机的本科生，现在在做一个基础的舆情分析系统，微博数据的获取，根据simple版本还是没能满足需求，simple版本的代码里是对单独三个id的数据的获取。我想要实现大量的用户的数据我理解的是：一种方法是根据其实id以及其关注和粉丝列表来递归获取，另一种是维护一个微博活跃用户池，就像大佬https://github.com/nghuyong/weibo-public-opinion-datasets里的思路一样，所以想请教大佬关于微博用户活跃池的代码程序

**Comment by nghuyong** [comment]
对的，需要有一部分的基础用户，才能通过“关注和粉丝列表来递归获取”

**Comment by SubDong** [comment]
按照这个系统的思路，是需要在上层自己构建一个种子获取，任务分发的系统么，也就是说现在这个系统只是一个任务执行器，没完全达到  种子 --->  收集 <---> 执行的目的嘛

**Comment by nghuyong** [comment]
就是把这个系统的 好友关注列表爬虫 和 个人主页爬虫 结合即可

**Comment by SubDong** [comment]
理解啦，但是现在weibo有个问题不知道大佬你们怎么解决的，就是关注和粉丝这两个类别里面最多只能查看到5月的数据，这个有办法突破么

**Comment by nghuyong** [comment]
抱歉，关注和粉丝的数量这个目前突破不了。
