### ISSUE TITLE
weibo.cn按小时检索关键词

### ISSUE THREAD

**Issue by konghr** [nghuyong/WeiboSpider#192]
程序可否设置成小时的呢，以便关键词搜索得到的内容更全

**Comment by nghuyong** [comment]
可以的，最近会有优化

**Comment by CharesFang** [comment]
[微博高级搜索](https://s.weibo.com/) s.weibo.com 可以实现精确到小时的搜索

**Comment by nghuyong** [comment]
目前来看还是只能精确到天...
不过对于微博搜索，我们构建了一种全新的方法，具体参见：https://github.com/nghuyong/weibo-public-opinion-datasets

**Comment by konghr** [comment]
感谢感谢！

**Comment by incandescentxxc** [comment]
实测发现了一个weibo.cn按任意小时间隔（每1h/2h/...)搜索关键词的方法：
在现有url构建的基础上，在日期后加上 “-x" (x是数字）。其中，starttime后-x表示指定时刻之后, endtime后-x表示指定时刻之前。x表示在现有日期下的小时偏移数(offset)，具体偏移规则应该是由微博制定，这里只能反推。
下面举例按小时搜索，以2020/2/19日为例：
starttime=20200217-40&endtime=20200217-17 表示2020/2/19 0:00am-1:00am。starttime部分表示20200219 0:00am之后。
...
starttime=20200217-46&endtime=20200217-23 表示2020/2/19 6:00am-7:00am。
starttime=20200218-23&endtime=20200218-0 表示2020/2/19 7:00am-8:00am。
starttime=20200218-24&endtime=20200218-1 表示2020/2/19 8:00am-9:00am。
....
starttime=20200218-39&endtime=20200218-16 表示2020/2/19 11:00pm-12:00am。
如果想放大时间间隔，只需将starttime后-x调小或将endtime后-x调大，测试发现，endtime的x不能为负且小于100。

**Comment by nghuyong** [comment]
非常赞的发现，你能否细致研究一下这个，然后发起一个PR～
@incandescentxxc

**Comment by callmeYe** [comment]
> 实测发现了一个weibo.cn按任意小时间隔（每1h/2h/...)搜索关键词的方法：
> 在现有url构建的基础上，在日期后加上 “-x" (x是数字）。其中，starttime后-x表示指定时刻之后, endtime后-x表示指定时刻之前。x表示在现有日期下的小时偏移数(offset)，具体偏移规则应该是由微博制定，这里只能反推。
> 下面举例按小时搜索，以2020/2/19日为例：
> starttime=20200217-40&endtime=20200217-17 表示2020/2/19 0:00am-1:00am。starttime部分表示20200219 0:00am之后。
> ...
> starttime=20200217-46&endtime=20200217-23 表示2020/2/19 6:00am-7:00am。
> starttime=20200218-23&endtime=20200218-0 表示2020/2/19 7:00am-8:00am。
> starttime=20200218-24&endtime=20200218-1 表示2020/2/19 8:00am-9:00am。
> ....
> starttime=20200218-39&endtime=20200218-16 表示2020/2/19 11:00pm-12:00am。
> 如果想放大时间间隔，只需将starttime后-x调小或将endtime后-x调大，测试发现，endtime的x不能为负且小于100。
补充：测试了一下想要表示2020/2/01 0:00am-1:00am的话，是starttime=20200130-40&endtime=20200130-17

**Comment by callmeYe** [comment]
starttime=20200130-40&endtime=20200130-17 表示2020/2/01 0:00am-1:00am
...
starttime=20200217-40&endtime=20200217-17 表示2020/2/19 0:00am-1:00am。
starttime=20200217-41&endtime=20200217-18 表示2020/2/19 1:00am-2:00am。
starttime=20200217-42&endtime=20200217-19 表示2020/2/19 2:00am-3:00am。
starttime=20200217-43&endtime=20200217-20 表示2020/2/19 3:00am-4:00am。
starttime=20200217-44&endtime=20200217-21 表示2020/2/19 4:00am-5:00am。
starttime=20200217-45&endtime=20200217-22 表示2020/2/19 5:00am-6:00am。
starttime=20200217-46&endtime=20200217-23 表示2020/2/19 6:00am-7:00am。
starttime=20200218-23&endtime=20200218-0 表示2020/2/19 7:00am-8:00am。
starttime=20200218-24&endtime=20200218-1 表示2020/2/19 8:00am-9:00am。
....
starttime=20200218-39&endtime=20200218-16 表示2020/2/19 11:00pm-12:00am。

**Comment by nghuyong** [comment]
@callmeYe @incandescentxxc 
我尝试检索 2021-1-13 日 00:00 - 01:00 之间的包含“北京”的关键词，构建URL: 
https://weibo.cn/search/mblog?hideSearchFrame=&keyword=%E5%8C%97%E4%BA%AC&advancedfilter=1&starttime=20210111-40&endtime=20210111-17&sort=time&page=1
但是只能查看第一页的数据，无法查看**第二页**
https://weibo.cn/search/mblog?hideSearchFrame=&keyword=%E5%8C%97%E4%BA%AC&advancedfilter=1&starttime=20210113&endtime=20210113&sort=time&page=2

**Comment by incandescentxxc** [comment]
@nghuyong 刚刚试了下这个例子，我这边测试还正常。但是之前确实出现过搜索一遍无法搜到内容，需要重新搜索的情况，而且这个问题在没有加小时搜索的时候也会偶尔出现。

**Comment by callmeYe** [comment]
> @callmeYe @incandescentxxc
> 我尝试检索 2021-1-13 日 00:00 - 01:00 之间的包含“北京”的关键词，构建URL:
> https://weibo.cn/search/mblog?hideSearchFrame=&keyword=%E5%8C%97%E4%BA%AC&advancedfilter=1&starttime=20210111-40&endtime=20210111-17&sort=time&page=1
> 查看后面2-100页的数据，不稳定，存在无法打开的情况。

直接跳页存在无法打开的情况，一直点击下一页可以

**Comment by nghuyong** [comment]
我测试了一下，「下一页」和「直接跳转」均存在无法搜到内容的几率，不过多刷新几次可以正常获取，可以添加重试机制

**Comment by CharesFang** [comment]
过了好久才看到这个issue，之前没有说清楚，在[微博高级搜索](https://s.weibo.com/) 这个页面中，提供了根据时间段检索微博的功能，具体的接口为 `https://s.weibo.com/weibo?q={keywords}&typeall=1&suball=1&timescope=custom:{start_time}:{end_time}&Refer=g`

其中的具体参数为
```
keywords: 搜索关键字，
start_time: 起始时间，格式为YYYY-MM-DD-H，如 ‘2021-03-03-3‘，
end_time: 截止时间，格式同上
```

简单测试了一下，在添加cookie的情况下能够返回得到具体的页面，给了几个例子可以测试一下：
https://s.weibo.com/weibo?q=iqoo&typeall=1&suball=1&timescope=custom:2021-03-03-3:2021-03-03-23&Refer=g
https://s.weibo.com/weibo?q=vivo&typeall=1&suball=1&timescope=custom:2021-03-04-8:2021-03-05-23&Refer=g

**Comment by nghuyong** [comment]
对的，不过我们关注的站点是weibo.cn

**Comment by nghuyong** [comment]
感谢大家的讨论，已优化并更新了代码，关键词的检索会先按照“天”的粒度进行检索：

如果检索结果的页数是100页，说明存在这一天可能存在更多的数据，继续对这一天按照“小时”的粒度进行二次检索；

如果页数不到100页，说明这一天的数据小于100页，已经都检索完毕，所以不用再按照小时进行检索，从而节省资源，提高速度。

@konghr  @CharesFang @incandescentxxc @callmeYe
