### ISSUE TITLE
大佬您好！求问怎么突破突破微博评论的50页限制呢？

### ISSUE THREAD

**Issue by YCSFiona** [nghuyong/WeiboSpider#193]
大佬您好！感谢您的项目！
我对于爬虫和网络前端都是新手，目前想要爬取一条微博下的所有评论，但是爬到50页后就无法爬取了。我检索了一下网络信息，发现微博限制了评论50页之后的内容查看，有些博主提议可以通过诸如日期检索的方式获取，但我困惑于该如何着手。
我的问题是，请问您的项目中有可以突破破微博评论的50页限制的办法吗？或者您是否可以方便给出一些操作建议？
万分感谢！！！🙏

**Comment by nghuyong** [comment]
目前来看还没有办法突破这个限制，获取全量的评论数据
