### ISSUE TITLE
关于指定id爬取用户微博的时间段设置问题-关键词似乎并非必填项

### ISSUE THREAD

**Issue by Qiegao1994** [nghuyong/WeiboSpider#194]
感谢分享代码！的确是目前测试过最稳定的爬虫!
想请教您一个关于抓取时间段设置的问题：我看了几个之前的issues，了解到weibo.cn对于单个用户微博筛选，关键词为必填项。但是我自己去weibo.cn选了一个用户测试了一下，虽然网页上写的关键词为（必填），但是可以空着不填，直接填写时间段，这样还是可以完成指定时间段筛选的，如下图所示：

![image](https://user-images.githubusercontent.com/60833574/102958066-0b3c5600-4517-11eb-8684-e48cb491c8e8.png)
今天是2020年12月23日，我选择的时间段是20201201-20201202
不筛选的话有，url是这样https://weibo.cn/2164376267/search?f=u&rl=1&hasori=0&haspic=0：
![image](https://user-images.githubusercontent.com/60833574/102958417-c2d16800-4517-11eb-8797-4549ee318578.png)

筛选的话，usl变成https://weibo.cn/2164376267/search?f=u&rl=1&hasori=0&haspic=0&starttime=20201201&endtime=20201202：
![image](https://user-images.githubusercontent.com/60833574/102958399-b77e3c80-4517-11eb-9c13-29cdd1c709a2.png)

并且我翻看了筛选后的微博，的确只现实20201201-20201202的用户微博。

这是不是说明，可以在这个代码的基础上添加时间段设置功能？

期待您的回复！

**Comment by Qiegao1994** [comment]
补充一下：筛选条件设置后，可以看到Form data这里变成这样了：
![image](https://user-images.githubusercontent.com/60833574/102959555-d3371200-451a-11eb-9faf-af70ec94ca97.png)
keywords是空着的~

**Comment by nghuyong** [comment]
你可以确认一下如果不填关键词筛选出来的总量是不是就是这个用户这段时间所发微博的总量

**Comment by Qiegao1994** [comment]
> 你可以确认一下如果不填关键词筛选出来的总量是不是就是这个用户这段时间所发微博的总量

您好~感谢回复。
我刚才选了好几个用户，测试了一番。我发现：
对于微博数量比较少的用户使用筛选时间段功能且不填关键词，是可以得到等量微博的。
比如：
一名用户总共有8页微博，我按照他第一次发微博的时间开始，筛选至今天，也同样得到了8页微博。数量一致。

但是如果该用户微博数特别多，筛选后的数量就对不上号了。
比如：
一名用户总共有10000页微博，我从第一条微博开始筛选到今天，虽然筛选后显示的页码也是10000页左右，但是大概只有前xxxx页有内容，后面的页码都是空页。这个xxxx页对于每个账号来说都不一样，有的删选后只能看到100来页，有的又能看到几千页，不知道是不是weibo.cn只返回一个百分比数量的微博。

以上。看来用这种筛选的方法的确不能精确保证获取某个时间段的微博了。

还有一个问题请教：能否通过匹配日期字符串的方式来实现指定时间段的功能呢？比如：当爬到某个日期时，就停止，继续爬下一位用户？或者每次计算created_date 和当前日期的差值，当差值达到某个数量时，就停止爬虫？

真心求教~

**Comment by nghuyong** [comment]
不用一次性获取所有的页数来爬，可以从第一页开始，一页一页的来爬，页面上有一个「下一页」
