### ISSUE TITLE
请教一个问题。

### ISSUE THREAD

**Issue by dbw5718** [nghuyong/WeiboSpider#195]
weibo.com中的内容有的是不是在weibo.cn中不会显示？昨天我爬取数据的时候对比了.com的，这是微博本身的问题还是爬虫数据丢失了。

**Comment by nghuyong** [comment]
比如说？能给一个具体的例子吗，weibo.com是什么weibo.cn是什么

**Comment by dbw5718** [comment]
就是有一些内容在weibo.com里可以搜索到，但是在weibo.cn里是没有这条数据的，这是啥问题导致的呢，就像下边两张图片显示的，weibo.cn里没有这条数据。
![Upl
![74374c8a81eb5bf75834f50f84ed469](https://user-images.githubusercontent.com/16859590/103655045-aca8ba80-4fa1-11eb-8f42-c4b742dc9df8.jpg)
![6558515999967dde1888a1c105c5f84](https://user-images.githubusercontent.com/16859590/103655055-b0d4d800-4fa1-11eb-933e-ee490d25386d.png)

**Comment by nghuyong** [comment]
![image](https://user-images.githubusercontent.com/16462374/103674093-4def3b00-4fb9-11eb-97d2-0e3a56f31782.png)
搜索进入高级检索，设置热门和时间段
