### ISSUE TITLE
有关数据过滤的bug

### ISSUE THREAD

**Issue by callmeYe** [nghuyong/WeiboSpider#199]
utils.py中定义的正则有些并没有起作用，比如 [组图共x张] 就没有被过滤，还有就是像http://t.cn/A6UeqHCv这样的链接也没有过滤，诸如“显示地图”这样的信息似乎也是多余的

**Comment by nghuyong** [comment]
你好， [组图共x张]  以及 显示地图 本身就没有设计要过滤

**Comment by callmeYe** [comment]
![image](https://user-images.githubusercontent.com/15107776/104397584-11f34180-5588-11eb-888e-9b30291cd4fb.png)
在正则中是有存在的

**Comment by nghuyong** [comment]
那应该是写bug了

**Comment by nghuyong** [comment]
关于[组图共.张]没有过滤的情况，是否是因为图片超过了9张，比如10张，所以正则修改为"[组图共**.+**张]"
