### ISSUE TITLE
抓取到的关注和粉丝数量不一致是为什么呢？

### ISSUE THREAD

**Issue by xinosaur** [nghuyong/WeiboSpider#20]
![1](https://user-images.githubusercontent.com/42018079/49422813-3ccb1300-f7d0-11e8-9602-8d71c23e2718.jpg)
![2](https://user-images.githubusercontent.com/42018079/49422816-3ccb1300-f7d0-11e8-8ad3-5a6cf8406eba.jpg)
如图(1)查看博主的关注数的粉丝数是185+84
图(2)通过爬虫抓取的关注数和粉丝数是232（178关注+54粉丝）
请问这是什么问题呢？

**Comment by nghuyong** [comment]
爬虫，只是抓取的那个时间点的，关注和粉丝数目，有一个crawl_time的字段

**Comment by xinosaur** [comment]
不太明白，不同的时间点数量应该也是一样的吧？

**Comment by xinosaur** [comment]
这个爬取的数量的话为什么会跟爬取的时间点有关呢

**Comment by xinosaur** [comment]
对，这肯定的。不过我想说的是，这个人的所有数据我都抓完了，通过抓取他的微博主页（也就是information这个表的数据）关注数和粉丝数是185和84，但是relationship这个表的关注数和粉丝数是178和54。也就是说，我感觉抓取的数据不完整，另外发现tweet数也不完整。所以我想问这是正常情况吗？还是因为什么

**Comment by xinosaur** [comment]
https://weibo.com/2803301701/like?#status
这个页面所有点赞过的微博，我觉得可以加上这个功能
另外在最开始的页面也还可以抓取微博的标签属性

**Comment by xinosaur** [comment]
collection.insert(dict())是不是可以用collection.save()替代呢

**Comment by fei-cheng** [comment]
`智能反垃圾系统自动清除了部分广告用户`, 如果分页去数，会发现你抓到的数目和数出来的数目是一致的
