### ISSUE TITLE
容器数量以及账号问题

### ISSUE THREAD

**Issue by victoriasunsun** [nghuyong/WeiboSpider#204]
docker小白想问问怎么增加容器数量到100个呀？
以及
我在爬虫的时候同时用20个账号就会出现cookie失效的状况（已用代理IP）
但是同时用5个就没问题

**Comment by nghuyong** [comment]
在portainer中可以直接修改容器数量，很方便的进行扩容
有限的cookie数量，只能支撑有限的爬虫进程。当然也跟每个爬虫进程中配置的`CONCURRENT_REQUESTS`与`DOWNLOAD_DELAY`有关

**Comment by victoriasunsun** [comment]
大佬！是不是这样就是两个容器同时进行呢？但是看logs怎么感觉两个爬虫都是一样的内容😭
| |
sunluqian_i
| |
|
sunluqian_i@pku.edu.cn
|
签名由网易邮箱大师定制


在2021年02月1日 16:51，HuYong<notifications@github.com> 写道：

Closed #204.
