### ISSUE TITLE
爬取特定博主在特定时间段内其下所有微博及其评论

### ISSUE THREAD

**Issue by Garethyu** [nghuyong/WeiboSpider#206]
入门级菜鸟请教：请问如何修改能够爬取指定博主在一定时间段内其下所有微博及其评论，目前我看在comment,py文件中只能爬取特定微博及其评论。

**Comment by victoriasunsun** [comment]
def init_user_tweets_spider():
    # crawl tweets post by users in particular time
    f= open('user.txt')
    user_ids = f.readlines()[0:10]
    #user_ids=['7171824166']
    date_start = datetime.datetime.strptime("2021-01-01", '%Y-%m-%d')
    date_end = datetime.datetime.strptime("2021-01-03", '%Y-%m-%d')
    time_spread = datetime.timedelta(days=1)
    urls = []
    url_format = "https://weibo.cn/{}/profile?hasori=0&haspic=0&starttime={}&endtime={}&advancedfilter=1&page=1"
    while date_start < date_end:
        for user_id in user_ids:
            one_day_back = date_start - time_spread
            # from today's 7:00-8:00am to 23:00-24:00am
            for hour in range(7, 24):
                # calculation rule of starting time: start_date 8:00am + offset:16
                begin_hour = one_day_back.strftime("%Y%m%d") + "-" + str(hour + 16)
                # calculation rule of ending time: (end_date+1) 8:00am + offset:-7
                end_hour = one_day_back.strftime("%Y%m%d") + "-" + str(hour - 7)
                urls.append(url_format.format(user_id,begin_hour, end_hour))
            two_day_back = one_day_back - time_spread
            # from today's 0:00-1:00am to 6:00-7:00am
            for hour in range(0, 7):
                # note the offset change bc we are two-days back now
                begin_hour = two_day_back.strftime("%Y%m%d") + "-" + str(hour + 40)
                end_hour = two_day_back.strftime("%Y%m%d") + "-" + str(hour + 17)
                urls.append(url_format.format(user_id,begin_hour, end_hour))
        date_start = date_start + time_spread
    redis_init('tweet_spider', urls)
        
    
    
    我重写了这个函数 感觉可以用

**Comment by Garethyu** [comment]
nghuyong您好：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 非常感谢您对我的问题的解答，现在我正用这个评论当作训练集，十分感激！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nghuyong/WeiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午2:18
收件人:&nbsp;"nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"宇哥"<278650413@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nghuyong/WeiboSpider] 爬取特定博主在特定时间段内其下所有微博及其评论 (#206)





 
def init_user_tweets_spider():
 # crawl tweets post by users in particular time
 f= open('user.txt')
 user_ids = f.readlines()[0:10]
 #user_ids=['7171824166']
 date_start = datetime.datetime.strptime("2021-01-01", '%Y-%m-%d')
 date_end = datetime.datetime.strptime("2021-01-03", '%Y-%m-%d')
 time_spread = datetime.timedelta(days=1)
 urls = []
 url_format = "https://weibo.cn/{}/profile?hasori=0&amp;haspic=0&amp;starttime={}&amp;endtime={}&amp;advancedfilter=1&amp;page=1"
 while date_start < date_end:
 for user_id in user_ids:
 one_day_back = date_start - time_spread
 # from today's 7:00-8:00am to 23:00-24:00am
 for hour in range(7, 24):
 # calculation rule of starting time: start_date 8:00am + offset:16
 begin_hour = one_day_back.strftime("%Y%m%d") + "-" + str(hour + 16)
 # calculation rule of ending time: (end_date+1) 8:00am + offset:-7
 end_hour = one_day_back.strftime("%Y%m%d") + "-" + str(hour - 7)
 urls.append(url_format.format(user_id,begin_hour, end_hour))
 two_day_back = one_day_back - time_spread
 # from today's 0:00-1:00am to 6:00-7:00am
 for hour in range(0, 7):
 # note the offset change bc we are two-days back now
 begin_hour = two_day_back.strftime("%Y%m%d") + "-" + str(hour + 40)
 end_hour = two_day_back.strftime("%Y%m%d") + "-" + str(hour + 17)
 urls.append(url_format.format(user_id,begin_hour, end_hour))
 date_start = date_start + time_spread
 redis_init('tweet_spider', urls)
 我重写了这个函数 感觉可以用

**Comment by nghuyong** [comment]
@Garethyu @victoriasunsun 
该功能已经集成，具体参见readme。
具体实现而言，一次检索的请求最多返回1000数据，为了提高效率，
我们假定一个用户20天内最多发1000条推文（50条/天），所以设置检索的时间段为20天。
