### ISSUE TITLE
镜像问题

### ISSUE THREAD

**Issue by victoriasunsun** [nghuyong/WeiboSpider#208]
之前是部署成功了的，但是今天出现了这个情况，请问是什么原因呢
<img width="1390" alt="截屏2021-03-03 下午7 24 22" src="https://user-images.githubusercontent.com/62976814/109800670-73669100-7c58-11eb-8f6a-d56f6e97e260.png">

**Comment by victoriasunsun** [comment]
就是replicas 后面的五个变成了0/1 没有启动成功 ，重新pull了镜像也没有用诶

**Comment by nghuyong** [comment]
第一个镜像成功启动了吗？

**Comment by victoriasunsun** [comment]
就是image是 registry.cn-hangzhou.aliyuncs.com/weibospider/spider:latest 的 就启动不成功诶
因为上午还没问题
我重新部署了也是那几个service不成功
不知道会不会是镜像出了问题

**Comment by nghuyong** [comment]
部署不成功的报错是什么呢？

**Comment by victoriasunsun** [comment]
我重启了docker就解决辽！
