### ISSUE TITLE
微博限制能看到的关注数量为5页

### ISSUE THREAD

**Issue by linzizhan** [nghuyong/WeiboSpider#21]
我在抓一个用户的所有关注时候发现weibo.com上只能看到5页，而weibo.cn上面能看到20页，但是这两个都无法看到全部的关注，这个问题有遇到过吗

**Comment by nghuyong** [comment]
是的，就是只能看到前20页。本身就是看不全的。

**Comment by linzizhan** [comment]
所以这里都只是前20页的数据是么，并不是全部的用户间的关注情况？

**Comment by nghuyong** [comment]
对，这是微博本身的限制
