### ISSUE TITLE
请问爬取的数据在哪里呢

### ISSUE THREAD

**Issue by Tourbition** [nghuyong/WeiboSpider#210]
我爬取玩数据之后，可以在终端看到数据，但是不知道数据存在什么地方，是在数据库中吗

**Comment by nghuyong** [comment]
对的，在mongo数据库中

**Comment by Tourbition** [comment]
那该怎么查看呢，我用的是mongo compass这个软件，没有在代码中找到连接链接connection string

**Comment by nghuyong** [comment]
在控制台能看到爬取数据的log吗
