### ISSUE TITLE
微博特定话题下的微博文本内容以及对应的评论等

### ISSUE THREAD

**Issue by imagineqsq** [nghuyong/WeiboSpider#214]
您好！我想爬取这些内容请问可以实现吗：一定时间内的特定话题下的微博内容，以及每条微博下的点赞数，转发数，以及评论内容等，比如我想爬取“新冠肺炎”这个话题。。

**Comment by nghuyong** [comment]
可以实现，需要组合“微博检索爬虫” 和 “评论爬虫”

**Comment by imagineqsq** [comment]
这两个功能都在项目里面吗？

**Comment by imagineqsq** [comment]
那个，我还想问一下，可以爬取微博网页版吗，就是weibo.com

**Comment by nghuyong** [comment]
1. 对，这两个功能都在该项目中，具体可以查阅readme
2. 目前不支持weibo.com

**Comment by imagineqsq** [comment]
好的，谢谢！辛苦了！
