### ISSUE TITLE
程序运行问题

### ISSUE THREAD

**Issue by 805477481** [nghuyong/WeiboSpider#219]
![QQ截图20210509204912](https://user-images.githubusercontent.com/44319750/117572970-08c64b80-b108-11eb-9445-f28dc43f9d63.png)

运行显示如图，请问大佬们是什么原因

**Comment by nghuyong** [comment]
不清楚，刚刚测试了一下在Python3.6环境下是可以正常运行的
请提供一下你的具体环境，包括Python，系统，scrapy版本等信息
