### ISSUE TITLE
Hi, is Weibo open for crawling now?

### ISSUE THREAD

**Issue by karmalet** [nghuyong/WeiboSpider#225]
I've done some crawling last year (around August 2020, from South Korea), but it is not working any more.
According to 'robots.txt', it seems Weibo now blocks crawling.
目前在中国爬取微博没问题吗？

https://weibo.cn/robots.txt
----------------------------
User-agent: *
Disallow: /
Allow: /dpool/ttt/
Disallow: /dpool/ttt/*gsid=*
Disallow: *gsid=*

**Comment by nghuyong** [comment]
根据robots协议是不允许的，所以目前该项目也仅作技术交流和学术使用。
