### ISSUE TITLE
`weibo.cn`搜索功能关闭，那么怎么才能实现抓取包含关键词的微博的功能呢？

### ISSUE THREAD

**Issue by Slian22** [nghuyong/WeiboSpider#226]
请求作者一个回答，感谢作者。

**Comment by ambitiousCC** [comment]
6.1就关闭搜索功能了。。。weibo.com也取消了高级搜索的功能，页面布局大改，主站html中内容也变成动态更新了，微博还会开放数据么。。。

**Comment by Xinyue-Wong** [comment]
同求，跪了T_T

**Comment by nghuyong** [comment]
感谢对该项目的持续关注，正在思考，近期会有更新

**Comment by dlb-shy** [comment]
我不懂为什么不使用m.weibo.cn来进行采集，这个可是不需要登陆

**Comment by BestLemoon** [comment]
weibo.com的接口感觉有点难过验证，m.weibo.cn应该可以寻找一下突破口

**Comment by dlb-shy** [comment]
app上的可以用，现在都在使用json传输数据

**Comment by nghuyong** [comment]
可以采用m.weibo.cn进行关键词微博的采集
