### ISSUE TITLE
有关WeiboSpider的视频url的疑问

### ISSUE THREAD

**Issue by ligujie123** [nghuyong/WeiboSpider#233]
我在使用您在Github上的WeiboSpider项目时，发现一些包含视频的微博并成功爬取没有video_url字段。例如爬取深圳卫视正午30分的微博时，其微博基本都包含视频（例如 https://weibo.com/1842606855/Ku1ei6zyb，
https://weibo.com/1842606855/Ku1dhclOS）。
不过在MongoDB中没有发现视频的相关字段。我用的是抓取用户的微博（指定时间段）功能。另外，我也发现，在爬数据的过程中，数据并不是严格按照时间顺序爬取的，例如八月的微博爬完之后，开始爬九月的微博，但是后来有显示爬取部分八月的微博，想请问一下这是否对最后爬取数据的质量有影响。谢谢！
![image](https://user-images.githubusercontent.com/29496632/137061403-db9a4d19-ec55-4130-95b6-c01a87d8fe72.png)

**Comment by nghuyong** [comment]
1. 关于微博视频
检查了一下，因为在微博的列表页没有显示微博视频的标记，只给了一个url，这个url会采集到content字段中。在该条微博的详情页是有「微博视频」的标记的。 这应该是早期的一种过度格式，现在最新的都是可以正常采集到视频字段的，所以代码层面就不做更新了。
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16462374/161538711-87019581-d70b-4cf7-8d85-97b13dd8a31c.png">

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/16462374/161538765-28dfec74-71ea-4e92-90cd-d52e541449e8.png">

2. 爬虫确实不是严格按照顺序爬的，不过总体数量应该是OK的，所以对质量没有影响。
