### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by MrSaiWang** [nghuyong/WeiboSpider#237]
我在安装lxml==3.8.0这个依赖时报错。

Collecting lxml==3.8.0
  Using cached lxml-3.8.0.tar.gz (3.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.
Installing collected packages: lxml
  Running setup.py install for lxml: started
  Running setup.py install for lxml: finished with status 'error'

  error: subprocess-exited-with-error
  
  Running setup.py install for lxml did not run successfully.
  exit code: 1
  
  [96 lines of output]
  Building lxml version 3.8.0.
  Building without Cython.
  ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running install
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\lxml
  copying src\lxml\builder.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\cssselect.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\sax.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\__init__.py -> build\lib.win-amd64-3.10\lxml
  creating build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.10\lxml\includes
  creating build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\builder.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\clean.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\defs.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\diff.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.10\lxml\html
  copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.10\lxml\html
  creating build\lib.win-amd64-3.10\lxml\isoschematron
  copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.10\lxml\isoschematron
  copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.10\lxml
  copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.10\lxml\includes
  copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.10\lxml\includes
  creating build\lib.win-amd64-3.10\lxml\isoschematron\resources
  creating build\lib.win-amd64-3.10\lxml\isoschematron\resources\rng
  copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\rng
  creating build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl
  creating build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.10\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building 'lxml.etree' extension
  creating build\temp.win-amd64-3.10
  creating build\temp.win-amd64-3.10\Release
  creating build\temp.win-amd64-3.10\Release\src
  creating build\temp.win-amd64-3.10\Release\src\lxml
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc\lxml\includes -IC:\fillit\python\include -IC:\fillit\python\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-3.10\Release\src\lxml\lxml.etree.obj -w
  cl : Command line warning D9025 : overriding '/W3' with '/w'
  lxml.etree.c
  src\lxml\includes\etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
  Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  creating Users
  creating Users\SAI
  creating Users\SAI\AppData
  creating Users\SAI\AppData\Local
  creating Users\SAI\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /TcC:\Users\SAI\AppData\Local\Temp\xmlXPathInit1z995t1z.c /FoUsers\SAI\AppData\Local\Temp\xmlXPathInit1z995t1z.obj
  xmlXPathInit1z995t1z.c
  C:\Users\SAI\AppData\Local\Temp\xmlXPathInit1z995t1z.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by nghuyong** [comment]
那直接 pip install lxm 试一试

**Comment by MrSaiWang** [comment]
谢谢。
直接安装lxml成功。最新版为4.7.1，但是python run_spider.py还是报错。

Traceback (most recent call last):
  File "C:\Users\SAI\Coding\WeiboSpider\weibospider\run_spider.py", line 11, in 
<module>
    from scrapy.crawler import CrawlerProcess
  File "C:\fillit\Python\lib\site-packages\scrapy\__init__.py", line 34, in <mod
ule>
    from scrapy.spiders import Spider
  File "C:\fillit\Python\lib\site-packages\scrapy\spiders\__init__.py", line 10,
 in <module>
    from scrapy.http import Request
  File "C:\fillit\Python\lib\site-packages\scrapy\http\__init__.py", line 8, in 
<module>
    from scrapy.http.headers import Headers
  File "C:\fillit\Python\lib\site-packages\scrapy\http\headers.py", line 3, in <
module>
    from scrapy.utils.datatypes import CaselessDict
  File "C:\fillit\Python\lib\site-packages\scrapy\utils\datatypes.py", line 11, 
in <module>
    from collections import OrderedDict, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\fillit\Python\l
ib\collections\__init__.py)

**Comment by nghuyong** [comment]
Python版本是3.6+吗？

**Comment by MrSaiWang** [comment]
是的， 3.10.2

**Comment by kasteria** [comment]
您好 我也碰到这个问题不能成功安装

**Comment by Cynthia-Ye** [comment]
也遇到类似的问题，我是python 3.9。已解决
应该是lxml==3.8.0版本安装有问题，pip install lxml直接安装最新版本的lxml依赖件。
后续运行run_spider.py时也遇到报错，虽然问题表现和你不一样，但是猜想是各组件的版本不匹配问题，最后采取的办法是：安装三个最新版本的依赖组件，即如果没有安装过组件，则运行：
pip install pymongo
pip install scrapy
pip install lxml
如果已安装了低版本的组件，则运行以下命令升级到最新版本：
pip install --upgrade pymongo
pip install --upgrade scrapy
pip install --upgrade lxml
处理后运行爬虫脚本，可正常爬取微博信息。

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦
