### ISSUE TITLE
评论爬17条在命令行就显示重复数据，爬400多条就说完成了。。。

### ISSUE THREAD

**Issue by ReganYue** [nghuyong/WeiboSpider#239]
评论爬17条在命令行就显示重复数据，爬400多条就说完成了。。。可是原微博有1.6万条。。。
![image](https://user-images.githubusercontent.com/20416270/159642386-1f8253dd-ece3-421a-8b2c-a83e8ef2eb99.png)

![image](https://user-images.githubusercontent.com/20416270/159642432-7401b849-0f33-4a03-a58c-171efb83c35f.png)

求救大佬~

**Comment by nghuyong** [comment]
评论数据本身就不能全部采集到，一般一个微博就能采集到200条评论左右
