### ISSUE TITLE
weibo.cn无法登陆获取cookie

### ISSUE THREAD

**Issue by SmilePoorCat** [nghuyong/WeiboSpider#24]
![image](https://user-images.githubusercontent.com/26210807/49633232-8b2c1c00-fa33-11e8-8300-5ee253217f3f.png)
![image](https://user-images.githubusercontent.com/26210807/49633321-e65e0e80-fa33-11e8-8218-d029e9e2d6d8.png)
像上面这个，我把代码图片校验的代码注释后发现cookie格式很异常，自行登陆发现，有个js包404了，人工都无法登陆了，更别说机器了，限制还是很大啊

**Comment by nghuyong** [comment]
是，大批量登陆账号是需要ip池的，同一个ip频繁登陆会封ip。
搭建ip池，可以参加我的另外一个项目https://github.com/nghuyong/ADSLProxy
