### ISSUE TITLE
pycharm中运行run_spider 报错 list index out of range，麻烦大佬解答一下

### ISSUE THREAD

**Issue by Tomhardy22** [nghuyong/WeiboSpider#248]
再pycharm中运行run_spider 报错 list index out of [range，麻烦大佬解答一下

**Comment by Tomhardy22** [comment]
in <module>
    mode = sys.argv[1]
IndexError: list index out of range

**Comment by Tomhardy22** [comment]
自己已解决...

**Comment by nghuyong** [comment]
大哥，你不能直接运行run_spider.py
得参考readme，填写一个参数，控制进行什么爬虫

**Comment by wangyilinzhiba** [comment]
哦莫好像是这个问题，谢谢

**Comment by yuanshi1221** [comment]
> 自己已解决...
请问您这是怎么样解决的啊？是如何添加参数的？

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦
