### ISSUE TITLE
wap站好像开始封IP了

### ISSUE THREAD

**Issue by joelYing** [nghuyong/WeiboSpider#25]
![image](https://user-images.githubusercontent.com/39625260/49708422-8d2bf000-fc6a-11e8-95dd-708bd96354a9.png)

**Comment by nghuyong** [comment]
你要控制好延迟

**Comment by nghuyong** [comment]
那应该是你的账号被封了，不是ip

**Comment by joelYing** [comment]
但是我用ss的代理的话还是可以获取数据的，所以应该帐号没被封...
