### ISSUE TITLE
如何进行关键词爬取

### ISSUE THREAD

**Issue by cauzp** [nghuyong/WeiboSpider#251]
您好，参考了您的代码，好像无法进行关键词搜索的爬取，只能针对用户特定时间段发布的微博进行爬取，请问想要进行关键词搜索爬取的话该如何进行呢？

**Comment by nghuyong** [comment]
感谢对该项目的关注，目前weibo.cn站点确实不支持针对关键词搜索进行采集。需要到weibo.com站点
