### ISSUE TITLE
weibo.cn粉丝列表最大只有20页

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [nghuyong/WeiboSpider#252]
现在看这个网页，粉丝最多只有20页，多了看不了，不知道有没有其它途径可以获取所有粉丝id

**Comment by Misaka-Mikoto-Tech** [comment]
https://github.com/sherwin/WeiboFansSpider
是否可以参考这个，搞个随机获取粉丝然后去重的功能？

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦
