### ISSUE TITLE
关于配置

### ISSUE THREAD

**Issue by Alpenl** [nghuyong/WeiboSpider#255]
作者你好，能不能出一个详细的配置方法，如如何配置爬取内容的时间范围

**Comment by nghuyong** [comment]
采集用户指定时间范围的微博
还是
采集搜索关键词时候指定时间范围的微博

**Comment by Alpenl** [comment]
采集搜索关键词时候指定时间范围的微博

**Comment by nghuyong** [comment]
https://github.com/nghuyong/WeiboSpider/blob/master/weibospider/spiders/search.py#L26
已经支持了哈

**Comment by Alpenl** [comment]
已收到，谢谢作者
另外还有一个挺重要的问题是设置文件保存格式，josn文件不太方便，如果可以的话增加保存为csv格式的挺好的

**Comment by nghuyong** [comment]
可以用很少的code自行转换存的数据格式哈，如果要转成csv可以参考这里：
https://stackoverflow.com/questions/65338470/json-lines-jsonl-generator-to-csv-format

**Comment by Alpenl** [comment]
收到，万分感谢
