### ISSUE TITLE
微博过长的话只能截取前半部分

### ISSUE THREAD

**Issue by stevaon** [nghuyong/WeiboSpider#256]
按照接口获取微博信息的时候，如果微博国产，只能截取前半部分，后面的内容获取不到了，这个能解决吗？
比如这个微博：https://weibo.com/ajax/statuses/show?id=4831081054344711
![image](https://user-images.githubusercontent.com/46243429/199725059-b7d146e4-4a09-40f5-a594-88eced46a7ea.png)

**Comment by nghuyong** [comment]
已经支持长微博全文的获取了～

**Comment by stevaon** [comment]
谢谢

HuYong ***@***.***> 于2022年11月3日周四 21:32写道：
