### ISSUE TITLE
weibo.com关键字搜索只显示50页

### ISSUE THREAD

**Issue by guanguxiansheng** [nghuyong/WeiboSpider#257]
作者大大，weibo.com关键字搜索，只能爬取前50页了，有办法突破吗？微博移动版好像没限制

**Comment by nghuyong** [comment]
可以这样试试，按照小时粒度拆分query；这样一天就可以产生24个搜索结果，每个50页，就有1200页的结果了

**Comment by guanguxiansheng** [comment]
> 可以这样试试，按照小时粒度拆分query；这样一天就可以产生24个搜索结果，每个50页，就有1200页的结果了
嗯但这样每个小时内，几乎都只能爬取前几分钟的搜索结果

**Comment by wxqssr** [comment]
> > 可以这样试试，按照小时粒度拆分query；这样一天就可以产生24个搜索结果，每个50页，就有1200页的结果了
> > 嗯但这样每个小时内，几乎都只能爬取前几分钟的搜索结果

我也是只能爬取前几几分钟的搜索结果

**Comment by nghuyong** [comment]
目前已经支持按照热度排序了，所以虽然不能突破50页的限制，但是可以采集到相对热门的前50页结果

**Comment by yucluo** [comment]
请问怎么才能按照热度排序啊，需要设置什么参数吗
