### ISSUE TITLE
ModuleNotFoundError: No module named 'spiders'

### ISSUE THREAD

**Issue by effock** [nghuyong/WeiboSpider#258]
小白想问一下大佬这个简单的问题
![error](https://user-images.githubusercontent.com/95751934/200788506-e7aef872-adc5-44eb-b1e8-a291263dca83.png)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\关键字查询\WeiboSpider-master\weibospider\spiders\search.py", line 10, in <module>
    from spiders.common import parse_tweet_info, parse_long_tweet
ModuleNotFoundError: No module named 'spiders'
from spiders.common import parse_tweet_info, parse_long_tweet
这一段话有3个地方报错，小白百度了半天都解决不了，大佬能不能帮忙看一下啊？感激不尽

**Comment by nghuyong** [comment]
在pycharm中的话，可以把weibospider这个文件夹设置为source root
<img width="451" alt="image" src="https://user-images.githubusercontent.com/16462374/200789574-5acb540e-25a6-4a04-b198-c441b044a1f5.png">

**Comment by effock** [comment]
![IMG_20221109_171944](https://user-images.githubusercontent.com/95751934/200790861-42a2c1ed-c9c1-4836-b1a6-4738b3fae414.jpg)
大佬，按您的方法试了一下，还是报错了

**Comment by nghuyong** [comment]
不能直接在pycharm点run执行，因为有命令行参数，请按照readme指引进行执行
```
cd weibospider
python run_spider.py user
```

**Comment by effock** [comment]
我是看了您的readme之后弄的，因为太小白了，所以不知道需要在哪里运行，就直接用pycharm打开了文件夹，也不想耽误您太多时间，请问大佬有相关的教程吗？拉取和安装我不知道在哪里运行，cmd里面识别不了，后面的cookie我替换了，运行程序的话我就不清楚具体需要怎么弄了

**Comment by nghuyong** [comment]
yisukeyan.com
建议你采用这个吧，点点鼠标就能采集数据了，具体可以按照网站的微信进行联系

**Comment by effock** [comment]
好的，谢谢大佬，我研究一下，我还是会学习一下怎么使用github上面的代码，感谢您在百忙之中抽出宝贵的时候来解答小白的问题，祝您工作顺利开心快乐！！！
