### ISSUE TITLE
请问代理目前还能用嘛？

### ISSUE THREAD

**Issue by BNDSllx** [nghuyong/WeiboSpider#268]
大家好，我本地IP爬取是没有问题的，但是在 `fetch_proxy` 里面加上代理 IP （return ip:port）后，就会超时然后报如下错误：

```
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

麻烦各位大佬帮我指出一下问题，是目前代理不能用了嘛？还是我用的不对？

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦

**Comment by nghuyong** [comment]
看起来是目前代理不能用了

**Comment by nghuyong** [comment]
可以使用，请参考 https://github.com/nghuyong/WeiboSpider/issues/124#issuecomment-654335439 设置代理
