### ISSUE TITLE
请问如何将微博发布地区确定在市级行政单位？

### ISSUE THREAD

**Issue by DuanJiaHao914** [nghuyong/WeiboSpider#270]
作者您好！目前爬取到的数据根据"ip_location"可以确定到省级行政单位，请问是否可能将微博发布地区确定在市级行政单位？非常感谢！

**Comment by nghuyong** [comment]
微博的对于ip地址只到省一级；但是对于用户的地区可以到市一级，可以在进一步采集user表中location获取
