### ISSUE TITLE
大佬可以设置爬取发布时间范围的配置吗

### ISSUE THREAD

**Issue by zhouyt168** [nghuyong/WeiboSpider#274]

**Comment by zhouyt168** [comment]
tweet 程序啥情况能停止爬取

**Comment by nghuyong** [comment]
可以的

**Comment by nghuyong** [comment]
感谢反馈，已经支持时间范围的配置
https://github.com/nghuyong/WeiboSpider/blob/master/weibospider/spiders/tweet_by_keyword.py#L28
