### ISSUE TITLE
ip代理设置以及数据量

### ISSUE THREAD

**Issue by Rocket-bw** [nghuyong/WeiboSpider#283]
在爬取数据的时候，如果不设置ip代理,请问是不是会有数量限制，比如说python run_spider.py search的时候，不设置ip总是爬了几百条就自动停止了。请问设置了 代理ip 后是不是能够解决这个问题啊

**Comment by bingo6666** [comment]
同问

**Comment by bingo6666** [comment]
我设置了隧道但还是这样，这是隧道使用情况，隧道应该是用起来了
![捕获](https://user-images.githubusercontent.com/110814635/232289099-ff5e4c06-0016-4256-ab95-8ea9e44cb30b.PNG)

**Comment by nghuyong** [comment]
对于关键词检索，如果想大规模采集，还需要配置账号池（目前是单个cookie）
