### ISSUE TITLE
[Bug Report] 关键词搜索，每次搜会爬到一堆无关的内容

### ISSUE THREAD

**Issue by yuzhangsjtu** [nghuyong/WeiboSpider#284]

**Comment by yuzhangsjtu** [comment]
而且每次获取的内容都只有几十条，按理说50页的结果，应该至少有几百条

**Comment by nghuyong** [comment]
有设置时间范围吗？
方便话可以给出具体的一个例子

**Comment by yuzhangsjtu** [comment]
作者好，感谢回复。
有设置时间范围的，我之前以#什么原因阻碍了你生小孩#为话题搜索，设置的范围是热搜后的三天，只搜出来几十条结果，里面夹杂着很多无关的明星八卦。

**Comment by nghuyong** [comment]
感谢反馈，已修复
