### ISSUE TITLE
用户博文爬取可以设置时间范围筛选吗？

### ISSUE THREAD

**Issue by wyycommu** [nghuyong/WeiboSpider#287]
如题，或者设置一个停止爬取的时间/页数条件也行，谢谢作者大大。不论如何，感谢您的项目，对我帮助很大！

**Comment by nghuyong** [comment]
已经支持了
https://github.com/nghuyong/WeiboSpider/blob/master/weibospider/spiders/tweet_by_keyword.py#L28
