### ISSUE TITLE
Repost issue

### ISSUE THREAD

**Issue by JunchengGuo** [nghuyong/WeiboSpider#292]
repost的抓取功能好像不能使用了，每次使用都只能抓取到几十条结果，请问这该如何解决呢？

**Comment by nghuyong** [comment]
有具体的例子吗

**Comment by Lupopro** [comment]
请问以主题来爬取的时候，关闭以小时切分时，为啥爬取500左右的数据就会自动停止呢？

**Comment by nghuyong** [comment]
最好给个具体的例子哈

**Comment by JunchengGuo** [comment]
> 有具体的例子吗

是可以用，但是对于大数据量大微博（比如6000的转发，）
       
        # 这里tweet_ids可替换成实际待采集的数据
        tweet_ids = ['Msz2Tjapl']

，只能爬取500-600条的转发微博，如果是小数量的 也会有一定的减少。只有在100以下的时候才会完整爬下来。使用关键词的爬取数据都能正常使用。

**Comment by nghuyong** [comment]
大数据量的转发从网页端正常浏览也是不能全部看到的，这是微博自身的限制
