### ISSUE TITLE
不知道是不是微博网址有变化了，运行此行代码，爬下来的内容不是start_uids里面uid的微博信息，需要把'/{}?page=1'改成'/{}/profile?page=1'

### ISSUE THREAD

**Issue by reedom1991** [nghuyong/WeiboSpider#3]
https://github.com/nghuyong/WeiboSpider/blob/a9bc097b944e11c231103e65b974a860f977605d/sina/spiders/weibo_spider.py#L88

**Comment by nghuyong** [comment]
我这里是OK的，事实上加入profile 和不加 都是可以访问用户微博的，如下面两个截图所示

![image](https://user-images.githubusercontent.com/16462374/45937153-3eb67000-bff0-11e8-9ee3-446b2e1f36c4.png)


![image](https://user-images.githubusercontent.com/16462374/45937110-dc5d6f80-bfef-11e8-8330-be2a48b5ce1d.png)
