### ISSUE TITLE
好像表情以及表情之后的文字都被丢弃了。

### ISSUE THREAD

**Issue by caolusg** [nghuyong/WeiboSpider#30]
是不是这样？还有个问题，当微博是转发的时候，好像只爬取了被转发的内容，而转发时候自己加的文字不被抓取？class = cmt还是 ctt那部分

**Comment by nghuyong** [comment]
表情还是在的哦，
![image](https://user-images.githubusercontent.com/16462374/52026230-101e4800-2542-11e9-825c-cedfcd7e7335.png)
比如这里的[星星]就是表情
