### ISSUE TITLE
请问有办法爬取2级评论吗？

### ISSUE THREAD

**Issue by wyycommu** [nghuyong/WeiboSpider#302]
首先感谢作者的付出。

实际使用了comment功能，发现无法爬取二级评论。

我只懂一些粗浅的原理，如果二级评论比较少的话，`data['comment']`会直接显示。如下图：
![image](https://github.com/nghuyong/WeiboSpider/assets/66957019/1860f1db-405e-4607-afc3-751445988cc0)

但是如果二级评论比较多的话，它会一折叠起来，我就拿它没办法了。如下图：

![image](https://github.com/nghuyong/WeiboSpider/assets/66957019/82ecc659-7022-4b28-9e06-f528254072e9)

此外，向您提一个bug：部分官方账号是不显示ip地址的，所以`item['ip_location'] = data['source']`这里如果没有获得信息的话，这条评论就会被跳过。这可能是部分评论抓取不到的原因。
关键字段加一个`try-except`或者`if "" in data·`，或许可以改善。

附上述问题相关的主要代码：
```
    def parse_comment(data):
        """
        解析comment
        """
        item = dict()
        item['created_at'] = parse_time(data['created_at'])
        item['_id'] = data['id']
        item['like_counts'] = data['like_counts']
        item['ip_location'] = data['source']
        item['content'] = data['text_raw']
        item['comment_user'] = parse_user_info(data['user'])
        return item
```

**Comment by nghuyong** [comment]
ip_location 已经修复了

**Comment by nghuyong** [comment]
已经支持了，默认打开的

二级评论会多一个字段`reply_comment`

**Comment by PengxiangZhou98Whu** [comment]
请问您这边解决问二级评论的问题了吗？我这边能抓到一些reply_comment, 但是不全。多个二级评论或者是只有一个二级评论都存在无法抓取的情况

**Comment by nghuyong** [comment]
方便提供一个具体的微博id（进行debug）

**Comment by PengxiangZhou98Whu** [comment]
https://weibo.com/3235040884/O1SHpzWoB?pagetype=profilefeed  这一条也可以，请问可以也指出

**Comment by PengxiangZhou98Whu** [comment]
> 方便提供一个具体的微博id（进行debug）

感谢您的回复！
https://weibo.com/3235040884/O1SHpzWoB?pagetype=profilefeed 这一条二级评论比较少，可以先看看这个。
另外这一条也是https://weibo.com/1749127163/O4cpumkS8，比较多的二级评论
