### ISSUE TITLE
关于数据量的问题

### ISSUE THREAD

**Issue by Rocket-bw** [nghuyong/WeiboSpider#306]
请问 这种APi获取数据的方法为什么不会触碰到微博的反爬措施呢，是不是说如果不设置代理也是会被官方反爬的啊，我看只有设置代理，没有设置多个账号，代码也只有100多行，为什么可以这么简单就获取数据啊

**Comment by nghuyong** [comment]
1. 因为填充了cookie，是有账号的。没有账号会遇到官方反爬
2. 单账号按照预设的速度是不会触发官方反爬系统的。速度更快就会遇到官方反爬
