### ISSUE TITLE
用户微博指定时间段下载

### ISSUE THREAD

**Issue by mamingsuper** [nghuyong/WeiboSpider#308]
感谢贡献给力的工具，想请问如果想爬取某个用户指定时间段内的微博是否可行？现在只是关键词搜索可以设置起止时间。如果用户微博爬取也可设置的话感觉会更加方便，感谢！

**Comment by nghuyong** [comment]
可行的，会尽快支持

**Comment by nghuyong** [comment]
已经支持，在这里设置

https://github.com/nghuyong/WeiboSpider/blob/master/weibospider/spiders/tweet_by_user_id.py#L30

**Comment by mamingsuper** [comment]
> 已经支持，在这里设置
> 
> https://github.com/nghuyong/WeiboSpider/blob/master/weibospider/spiders/tweet_by_user_id.py#L30

完美解决，非常感谢！
