### ISSUE TITLE
可以爬访客记录吗？

### ISSUE THREAD

**Issue by wuliqiangqiang** [nghuyong/WeiboSpider#309]

**Comment by nghuyong** [comment]
微博本身能看到访客记录吗？

**Comment by nghuyong** [comment]
方便截图看一下具体位置吗？

**Comment by wuliqiangqiang** [comment]
> 方便截图看一下具体位置吗？

@nghuyong 
![WechatIMG182](https://github.com/nghuyong/WeiboSpider/assets/16221367/7c7d4425-3be7-4bfb-9177-bd3d2edd9dc3)

**Comment by nghuyong** [comment]
😯，web端可以看到吗？目前不支持app端的采集

**Comment by wuliqiangqiang** [comment]
> 😯，web端可以看到吗？目前不支持app端的采集

web端看不到，那没法子了
