### ISSUE TITLE
search 分支打开多个进程不久后一直显示 XXXpages crawled 0 pages per minute. 关掉多个进程以后几分钟再开，才开始爬。好像只能一个进程？？？

### ISSUE THREAD

**Issue by caolusg** [nghuyong/WeiboSpider#31]

**Comment by caolusg** [comment]
那应该怎么做？这种ip封锁，还会解除封锁吗？

HuYong <notifications@github.com>于2019年1月31日 周四09:28写道：

**Comment by nghuyong** [comment]
会解除，不过需要一段时间。我会更新一下代码，对IP被封的检测

**Comment by caolusg** [comment]
谢谢你。或者我可不可以用不断变换自己机器ip的方式解决？

HuYong <notifications@github.com>于2019年1月31日 周四10:15写道：

**Comment by nghuyong** [comment]
可以，我已经更新了ip封锁的检测，你只需要加一个代理IP的中间件即可

**Comment by caolusg** [comment]
太好了。谢谢你。我现在就看一下。

HuYong <notifications@github.com>于2019年1月31日 周四10:21写道：

**Comment by caolusg** [comment]
看来ip被封锁是个大问题，要想专门的办法解决了？


Best Regards,
Cao Lu

**Comment by nghuyong** [comment]
是，建议自己构建ip池
