### ISSUE TITLE
写完不测试的吗

### ISSUE THREAD

**Issue by kusen-alpha** [nghuyong/WeiboSpider#310]
循环使用变量时，不注意类型。

![Uploading 微信图片_20231214115522.png…]()

**Comment by kusen-alpha** [comment]
![1702526120546](https://github.com/nghuyong/WeiboSpider/assets/71452054/0d6e97ad-434f-4a18-94e1-3603b78b74d3)

**Comment by nghuyong** [comment]
大意了，已fix

**Comment by kusen-alpha** [comment]
评论数据可以加一下原文id和多级评论记录一下上一级评论id
