### ISSUE TITLE
按指示git clone时报错

### ISSUE THREAD

**Issue by xiongot** [nghuyong/WeiboSpider#311]
git clone git@github.com:nghuyong/WeiboSpider.git --depth 1 --no-single-branch
Cloning into 'WeiboSpider'...
The authenticity of host 'github.com (20.205.243.166)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,20.205.243.166' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by blacksh1982** [comment]
遇到了同样的问题呢。

**Comment by nghuyong** [comment]
可以尝试通过https的方式拉code

```
git clone https://github.com/nghuyong/WeiboSpider.git --depth 1 --no-single-branch
```
