### ISSUE TITLE
溯源问题

### ISSUE THREAD

**Issue by freeze-l** [nghuyong/WeiboSpider#314]
你好，我想请问一下，利用关键字检索的结果，会有很多转发的微博都被爬取下来，我能否判断该条微博是转发还是源头微博呢？

**Comment by nghuyong** [comment]
已经支持

is_retweet: true 表示该推文是转发的推文，通过retweet_id可以进一步获取到原推文的id

**Comment by freeze-l** [comment]
你好，我在之前有引用并改写过您的项目，我现在想要获取这个is_retweet字段，我想知道我应该更新哪个文件呢

**Comment by nghuyong** [comment]
https://github.com/nghuyong/WeiboSpider/blob/master/weibospider/spiders/common.py#L86

改动是这个函数
