### ISSUE TITLE
账号池的方法已经完全没法用了。前几天还可以

### ISSUE THREAD

**Issue by caolusg** [nghuyong/WeiboSpider#32]
前几天一天爬过800万数据，昨天开始突然开始封锁ip了。不知道换了其他ip会不会解决。作者有没有计划做一个破解封锁ip的版本？还有，能确定418是ip被封锁的代码吗？因为我发现这个所谓的封锁，好像不一会就可以再次用了。会不会不是ip封锁的原因？

**Comment by nghuyong** [comment]
我加上了ip池，已经可以解决了。我也不确定418到底是不是ip封锁，不过换了ip确实可以解决

**Comment by caolusg** [comment]
可否分享一下加ip池的代码和配置步骤？

HuYong <notifications@github.com>于2019年1月31日 周四14:01写道：
