### ISSUE TITLE
写入jsonl文件的代码在哪个位置？

### ISSUE THREAD

**Issue by Juice113** [nghuyong/WeiboSpider#324]
我在piplines.py中找到了写入函数，但是在程序运行流程的代码中没发现有调用pipelines.py，想问下是在哪里执行了写入jsonl文件？

**Comment by pyvadev** [comment]
请具体描述一下问题，贴一下你的代码，执行的是哪个 spider，爬的什么数据，是如何确认 piplines.py 中的函数没有被调用的

**Comment by nghuyong** [comment]
@Juice113  scrapy框架会自动调用pipeline的
