### ISSUE TITLE
对于有位置的微博， geo字段会呈现数据吗？

### ISSUE THREAD

**Issue by Godmyhave** [nghuyong/WeiboSpider#328]

**Comment by nghuyong** [comment]
会的，参考readme中的例子

https://github.com/nghuyong/WeiboSpider?tab=readme-ov-file#%E5%9F%BA%E4%BA%8E%E5%85%B3%E9%94%AE%E8%AF%8D%E7%9A%84%E5%BE%AE%E5%8D%9A%E9%87%87%E9%9B%86
