### ISSUE TITLE
可否分享一下构建ip池的代码和步骤

### ISSUE THREAD

**Issue by caolusg** [nghuyong/WeiboSpider#33]
非常感谢！

**Comment by nghuyong** [comment]
好，我这几天寻找一下好的代理池。
这是我自己构建ADSL代理池的方法：https://github.com/nghuyong/ADSLProxy

**Comment by caolusg** [comment]
> 好，我这几天寻找一下好的代理池。
> 这是我自己构建ADSL代理池的方法：https://github.com/nghuyong/ADSLProxy

请问这种方式是每个访问都给一个ip吗？还是给所有的访问同一个ip？

我刚才看到有方法可以通过middleware随机拿一个放在ip池里面的ip去访问。但是这样的话，会不会出现微博发现一个账号短时间用不同的ip去访问导致被封锁？

**Comment by nghuyong** [comment]
1. ADSL的设置的是每个5分钟(可以自己指定)拨号一次，也就换了一个新的ip
2. 这个IP和账号是否会关联检测，目前还没注意
3. 有可能微博的人盯上这个项目了，忐忑。。。

**Comment by OHKUE** [comment]
请问重复出现
`2019-01-31 23:09:46 [scrapy.extensions.logstats] INFO: Crawled 15910 pages (at 0 pages/min), scraped 20468 items (at 0 items/min)`
是否和IP有关？
IP池该如何在爬虫中使用呢？
谢谢！

**Comment by buwanglsc** [comment]
想问OHKUE，有没有出现“ip 被封了!!!请更换ip,或者停止程序...”的错误提示？

**Comment by nghuyong** [comment]
已经加入了代理IP的逻辑，请根据readme更新
