### ISSUE TITLE
第一个字符丢失

### ISSUE THREAD

**Issue by QishengLi** [nghuyong/WeiboSpider#40]
https://github.com/nghuyong/WeiboSpider/blob/b5acb4f2985cbfa4278e765b41a50efebc2746a9/sina/spiders/weibo_spider.py#L172

这里应该是all_content[0:]？

**Comment by nghuyong** [comment]
没有丢失，去除的是:

**Comment by QishengLi** [comment]
我自己试了一下branch`simple`，得到的内容是没有第一个字符的...
