### ISSUE TITLE
爬取数据不全

### ISSUE THREAD

**Issue by OHKUE** [nghuyong/WeiboSpider#41]
您好，我发现有好几天的数据只爬到了下午5点之后的，通过手动搜索发现当天5点之前也有数据，但就是爬不到，请问是为什么呀？该如何解决？多谢！

**Comment by nghuyong** [comment]
你解决了代理IP问题？

**Comment by OHKUE** [comment]
> 你解决了代理IP问题？

我增加代理IP池后重新试了一下，还是存在这个问题。
