### ISSUE TITLE
单条微博内容你抓全了吗

### ISSUE THREAD

**Issue by mkx-python** [nghuyong/WeiboSpider#42]
单条微博你只获取 tweet_node.xpath('.//span[@class="ctt"]')[0] 这span标签里的text，微博内容获取的不全吧，有些在span标签外边的，你是怎么解决的

**Comment by nghuyong** [comment]
请举例说明

**Comment by mkx-python** [comment]
你看下人民日报2/24日12:07发的那条新闻

**Comment by nghuyong** [comment]
确实，这个是一bug，谢谢
