### ISSUE TITLE
单机版今天出现连接失败

### ISSUE THREAD

**Issue by LiuBaoxi** [nghuyong/WeiboSpider#43]
![_20190304201738](https://user-images.githubusercontent.com/10847839/53733015-9bc92280-3eba-11e9-9257-f533099cb76e.png)
白天单机版还好好的，晚上突然就出现上图错误，换了账号和IP都不行，请问大家今天也是这样吗

**Comment by nghuyong** [comment]
应该不是吧，我这里还是正常的
