### ISSUE TITLE
无法获取cookies

### ISSUE THREAD

**Issue by Powerrrrrr** [nghuyong/WeiboSpider#50]
![image](https://user-images.githubusercontent.com/26767631/55319337-395a4680-54a7-11e9-991c-a991735874ee.png)

**Comment by valar000** [comment]
账号要点验证码，我的提交上用chromedriver 修复了（需要手动点验证码）

**Comment by Powerrrrrr** [comment]
啊，这个我知道，不过我自己实现了，就不需要这个代码了。
谢谢你啦！麻烦了。

**Comment by zxaiyl** [comment]
我也遇到这个情况，是怎么解决的？

**Comment by valar000** [comment]
敏感账号，要手动验证，

zxaiyl <notifications@github.com<mailto:notifications@github.com>> 于 2019年6月25日周二 下午10:34写道：

我也遇到这个情况，是怎么解决的？

**Comment by nghuyong** [comment]
请购买无需验证码的账号
