### ISSUE TITLE
如何在这个代码的基础上加入IP池？

### ISSUE THREAD

**Issue by Qiegaocode** [nghuyong/WeiboSpider#53]
如题，这个爬虫超级棒！但这几天使用后发现，几乎几分钟就会被提示“[weibo_spider] ERROR: ip 被封了!!!请更换ip,或者停止程序...”, 想请教一下：如何在源代码中加入IP池

**Comment by nghuyong** [comment]
已经加入了代理IP的逻辑，请根据readme更新
