### ISSUE TITLE
爬取文本不全，表情 后面的文本会丢失。

### ISSUE THREAD

**Issue by Qiegaocode** [nghuyong/WeiboSpider#54]
![image](https://user-images.githubusercontent.com/48046990/55575264-13e86980-5741-11e9-8960-026e945c87a3.png)

如图所示，爬取的文本只到表情之前

![image](https://user-images.githubusercontent.com/48046990/55575247-0632e400-5741-11e9-9031-8746a115e972.png)

**Comment by Qiegaocode** [comment]
请问，如何修改代码可以解决这个小问题？

**Comment by nghuyong** [comment]
谢谢，代码已经更新，请拉取一下最新的代码，这个问题已经解决了

**Comment by Qiegaocode** [comment]
太感谢了！！！我试试新的


| |
张皖疆
|
|
邮箱：zhangwanjiang_job@163.com
|

签名由 网易邮箱大师 定制

在2019年04月05日 11:41，HuYong 写道：

谢谢，代码已经更新，请拉取一下最新的代码，这个问题已经解决了

**Comment by Qiegaocode** [comment]
你好！ 我现在在进行一项学术研究，需要爬取涉及某个关键词的全部微博文本及发布者信息，我试验了你的代码（很酷！很赞！），但美中不足的是受限于微博自身的数据限制，每次只能爬取50页内容，无法获得全部样本。我想请教一下，你可以实现微博某一关键词全部样本的爬虫吗？

在 2019-04-05 11:41:47，"HuYong" <notifications@github.com> 写道：


Closed #54.

**Comment by nghuyong** [comment]
是的，目前只能获得一个关键词，指定一天50页的数据

**Comment by Qiegaocode** [comment]
好的，谢谢解答！


| |
张皖疆
|
|
邮箱：zhangwanjiang_job@163.com
|

签名由 网易邮箱大师 定制

在2019年04月05日 12:15，HuYong 写道：

是的，目前只能获得一个关键词，指定一天50页的数据

**Comment by Qiegaocode** [comment]
主题：关于微博爬虫

你好！
我试用了你今晨新修改的代码，确实解决了之前的问题，现在表情后面的文字也会正常爬取了。


但是又出现了一个新的问题：
一般出现在转发内容中，如下图所示：
爬到的内容仅仅是“大理电视台”五个字
如下图所示：
我看了一下出现这种情况的，都是转发的微博。


这个应该是content部分抓取代码的问题吧？小白我也不太懂。。。。


假期打扰了！




 







在 2019-04-05 12:15:53，"HuYong" <notifications@github.com> 写道：


是的，目前只能获得一个关键词，指定一天50页的数据

**Comment by Qiegaocode** [comment]
你好！
我试用了你今晨新修改的代码，确实解决了之前的问题，现在表情后面的文字也会正常爬取了。


但是又出现了一个新的问题：
一般出现在转发内容中，如下图所示：







但实际获取到的微博如下图所示：




想请教一下，这个应该是content部分抓取代码的问题吧？


假期打扰了！万分抱歉!



 







在 2019-04-05 12:15:53，"HuYong" <notifications@github.com> 写道：


是的，目前只能获得一个关键词，指定一天50页的数据

**Comment by Qiegaocode** [comment]
你好！
我试用了你今晨新修改的代码，确实解决了之前的问题，现在表情后面的文字也会正常爬取了。

但是又出现了一个新的问题：
一般出现在转发内容中，如下图所示：
![image](https://user-images.githubusercontent.com/48046990/55615676-936a4d00-57c2-11e9-9c73-56addc5c82a6.png)
但实际获取到的微博如下图所示：
![image](https://user-images.githubusercontent.com/48046990/55615696-a250ff80-57c2-11e9-85ff-c874e83e10e7.png)
想请教一下，这个应该是content部分抓取代码的问题吧？
假期打扰了！万分抱歉!

**Comment by nghuyong** [comment]
没事，谢谢提醒，代码已经更新了

**Comment by zongjingyao** [comment]
你好，表情的问题好像还在，我刚拉的最新代码，simple分支。评论和转发里都有这个问题。
这有两个例子。
评论：
https://www.weibo.com/1965334051/B1I7yAJlz
![image](https://user-images.githubusercontent.com/2386640/55926381-a73f0480-5c43-11e9-8206-fd8787147914.png)

转发：
https://www.weibo.com/1965334051/AFDDXghUb
![image](https://user-images.githubusercontent.com/2386640/55926409-c473d300-5c43-11e9-9c16-045d0bacb203.png)

**Comment by nghuyong** [comment]
收到
