### ISSUE TITLE
转发的微博里原始内容不会被抓取下来吗？

### ISSUE THREAD

**Issue by zongjingyao** [nghuyong/WeiboSpider#55]
举个例子：
https://weibo.com/1965334051/HeDDqbPpP
这个微博里只抓取到了我转发的内容，没有原始微博里的内容。
![image](https://user-images.githubusercontent.com/2386640/55927096-62689d00-5c46-11e9-971f-40361046c37a.png)

**Comment by nghuyong** [comment]
对，不会抓取原始文本
