### ISSUE TITLE
模拟登陆有问题

### ISSUE THREAD

**Issue by shimachao** [nghuyong/WeiboSpider#62]
我把PhantomJS换成Chrome后发现登陆过程需要点一个验证，而且登陆后的页面是 https://m.weibo.cn/?sudaref=security.weibo.com，标题根本不会变成“我的首页”，所以：
WebDriverWait(self.browser, 30).until(
            EC.title_is('我的首页')
        )
抛出超时异常

**Comment by nghuyong** [comment]
说明这个账号异常，请按照readme中的引导购买账号
