### ISSUE TITLE
content bug

### ISSUE THREAD

**Issue by caolusg** [nghuyong/WeiboSpider#63]
https://www.weibo.com/5998975460/FDQErd6zk?type=comment

The crawled content is  '00~15', the actual content is '发表了博文《周四（01-11）实盘狙击捕捉热点（上午版）》欢迎来到张驰实盘直播间，本直播每日9:00~15:00为大家直播最新、最准、最全的股市信息，并提供客观有价值的行情分析、密切跟踪市场热点，火速'

**Comment by nghuyong** [comment]
是，这是一个bug

**Comment by caolusg** [comment]
可以帮忙fix一下吗？谢谢

**Comment by nghuyong** [comment]
![](http://image.nghuyong.top/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-05-07%20%E4%B8%8A%E5%8D%8811.07.21.png)
已经fix了，请拉去最新代码
