### ISSUE TITLE
关于大量账号和ip问题

### ISSUE THREAD

**Issue by fanyao1983** [nghuyong/WeiboSpider#64]
作者你好，一直有几个问题想请教，联系不上你
1.我有大量账号。要用代理ip申请吗，还是一个ip申请几千个号
2..com的貌似1-2天cookie就失效，需要重新login，有什么办法维持持久点。
3.获取cookie的时候，很多时候账号有问题，在location那个regex获取的地方没有很好的说明
4.账号是否监测ip？我跑下来的结果微博似乎是识别ip的，比方说在获取.cn的cookie的时候，不换ip，整几个就获取不了cookie了

**Comment by nghuyong** [comment]
1. 如果账号量很大，需要用代理IP获取账号的cookie
2. 本工作的爬虫针对的是cn站点，cn站点cookie能维持半个月，并不清楚com站点
3. 请根据readme的说明，购买正确的账号类型
4. 请看1
另外，已经加入了代理IP的逻辑，请根据readme更新

**Comment by fanyao1983** [comment]
谢谢作者
