### ISSUE TITLE
关于代理IP作者有什么推荐的

### ISSUE THREAD

**Issue by LiuBaoxi** [nghuyong/WeiboSpider#71]
如题，关于代理IP作者有什么好的推荐吗，之前用这份代码，启动12个爬虫一起爬，每个爬虫爬取间隔也很小，大概0.3秒左右吧，感觉效率很高。

请问作者现在这份sinor 代码，理论最高效率是怎么样的

**Comment by nghuyong** [comment]
理论效率取决于代理IP的质量
我目前代理的速度是100page/min

**Comment by LiuBaoxi** [comment]
请问你是开了多少线程，另外我用的阿布云，感觉好贵啊

**Comment by nghuyong** [comment]
64线程，我用的是 无忧代理

**Comment by ethanchans** [comment]
有个问题咨询下，登录时的IP和每次访问请求的IP需要是一样的吗？  我现在每次请求IP都是随机取的，被封了好多账号。 你们代理IP怎么用的？

**Comment by nghuyong** [comment]
不需要一致，账号被封不是这个原因。
应该是你的速度过快，导致了账号被封

**Comment by xiaoliangLLL** [comment]
小号商城被封了？？

**Comment by AngerBegins** [comment]
小号商城进不去了，你是在哪里买的号？？

**Comment by AngerBegins** [comment]
构建账号池，要换IP，怎么解决

**Comment by xiaoliangLLL** [comment]
购买小号的网站好像被封了


------------------ 原始邮件 ------------------
发件人: "AngerBegins"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 下午2:11
收件人: "nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com>;
抄送: "无法遮掩旳痛"<1044052875@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [nghuyong/WeiboSpider] 关于代理IP作者有什么推荐的 (#71)




构建账号池，要换IP，怎么解决
