### ISSUE TITLE
关键词检索

### ISSUE THREAD

**Issue by rrsun** [nghuyong/WeiboSpider#78]
你好，我想请问一下，为何根据关键词检索爬取的微博博文与关键词无关呢，这个关键词检索检索依据什么原理进行的呢？

**Comment by nghuyong** [comment]
不可能啊，你用的是search分支吗

**Comment by rrsun** [comment]
> 不可能啊，你用的是search分支吗

今天重新弄了一下，发现可以了，谢谢！
