### ISSUE TITLE
表情符号字段在哪

### ISSUE THREAD

**Issue by InterFisher** [nghuyong/WeiboSpider#79]

**Comment by nghuyong** [comment]
在正文中，形如 [微笑] 的文字实际上就是表情

**Comment by InterFisher** [comment]
> 在正文中，形如 [微笑] 的文字实际上就是表情

有没有考虑把它单独拿出来作为一个字段，因为还得自己去切割获取表情符号

**Comment by nghuyong** [comment]
一行正则即可获取，所以就没单独拿出来了

**Comment by InterFisher** [comment]
关于账号池问题，我往里面放了4个账号，运行login.py以后只有2个获取cookie成功，并且将对应的账号创建在了数据库中;可是另外两个账号却没有用到，控制台只是打印出了"Message："。然后我使用这两个账号运行weibo_spider.py的时候运行一两分钟就出现了ip被封的信息。这个应该如何解决。

**Comment by nghuyong** [comment]
1. 增加更多的账号，比如100个这种级别，肯定会有不可用的账号（可能已经被封了）
2. 采用simple分支，不要速度过快
