### ISSUE TITLE
爬不到任何数据 空跑

### ISSUE THREAD

**Issue by PeiyuXu** [nghuyong/WeiboSpider#80]
INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
用search爬虫时候，出现了上面的代码，什么也没有爬到。没有加入代理IP。

**Comment by nghuyong** [comment]
你是什么分支？请按照你所在的分支的readme的步骤来进行

**Comment by PeiyuXu** [comment]
> 你是什么分支？请按照你所在的分支的readme的步骤来进行

search分支。已经配置好了phantomjs, redis, mongodb. 账号池也可以正常构建。关键字和时间也填写好了。就是没有数据。
