### ISSUE TITLE
你好，爬取的微博评论数据不全

### ISSUE THREAD

**Issue by ALMA6** [nghuyong/WeiboSpider#81]
你好，首先感谢大神编的python代码，受益匪浅，为你的无私点赞，然后我有几个问题想咨询下：

1. 我使用simple版本的，查看了一下我抓取的微博数据，Tweets和Comments对不上，比如说固定某一个Tweets，他对应的评论正常有23条，但是抓取的Comments显示只抓取了10条，并且这10条并不是连续的10条，好像随她喜欢，喜欢哪条评论抓哪条，这是什么原因？

2.simple版本可以抓取固定某个时间段的数据么？比如2018年-至今

**Comment by nghuyong** [comment]
已经邮件回复。
