### ISSUE TITLE
Scrapy被反爬虫了

### ISSUE THREAD

**Issue by xhlgogo** [nghuyong/WeiboSpider#82]
simple版本：
settings.py：cookie和user_agent更换为自己的版本后，一次都没有成功过，显示如下：
”TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.“

**Comment by supercao2016** [comment]
ModuleNotFoundError: No module named 'sina.items'

**Comment by nghuyong** [comment]
请按照readme配置运行目录
