### ISSUE TITLE
mongodb中没有数据存储

### ISSUE THREAD

**Issue by Ryan0lb** [nghuyong/WeiboSpider#83]
登录成功，爬取成功，但是数据库没有搜寻到数据

**Comment by nghuyong** [comment]
你用的是哪个分支

**Comment by Ryan0lb** [comment]
Search分支，账户的数据也没在数据库发现，找到了Sina数据库，但是没有数据存储

**Comment by nghuyong** [comment]
你已经成功执行了login吗？
login的输出截图看一下？

**Comment by Ryan0lb** [comment]
成功执行了，爬虫都可以跑起来抓到数据
![图片](https://user-images.githubusercontent.com/15329046/61603664-0fed4280-ac71-11e9-9576-667d74fa2c2c.png)

**Comment by nghuyong** [comment]
Well done!
