### ISSUE TITLE
构建帐号池失败

### ISSUE THREAD

**Issue by zezhishao** [nghuyong/WeiboSpider#84]
```python
        WebDriverWait(self.browser, 30).until(
            EC.title_is('我的首页')
        )
```
出错，但是没有返回任何信息：
![image](https://user-images.githubusercontent.com/33691477/61692461-4786e800-ad60-11e9-8b08-6aa225e479bd.png)

请问这个问题是什么导致的又该如何解决呢？

多谢！

**Comment by nghuyong** [comment]
你的账号需要验证码，请按照readme指引购买不需要验证码的小号

**Comment by zezhishao** [comment]
> 你的账号需要验证码，请按照readme指引购买不需要验证码的小号

谢谢回复！
README中的[小号购买网站](www.xiaohao.shop)已经500了（已翻墙），请问有什么其他好的购买途径吗？我买了一些网站的，但都是同样的结果。

**Comment by zezhishao** [comment]
> 你的账号需要验证码，请按照readme指引购买不需要验证码的小号

找到网站了，感谢！
