### ISSUE TITLE
获取更多的关注人

### ISSUE THREAD

**Issue by sjpmpzx** [nghuyong/WeiboSpider#88]
通过 https://weibo.cn/attgroup/change?cat=user&uid= xxxxxxxxxx 似乎能抓取到更多的关注人

如：新华社 https://weibo.cn/attgroup/change?cat=user&uid=1699432410
![新华视点的所有关注人](https://user-images.githubusercontent.com/48707379/62828339-94f4b900-bb98-11e9-893d-e27c4186e815.jpg)

随便试了几个id，从页数来看大多数情况下返回的估计是全部关注人了；唯一的例外是人民日报，显示关注3000+但是只有34页
https://weibo.cn/attgroup/change?cat=user&uid=2803301701
![人民日报的所有关注人](https://user-images.githubusercontent.com/48707379/62828371-94105700-bb99-11e9-9bbf-024af4c5e30e.jpg)

**Comment by MR3118** [comment]
> 通过 https://weibo.cn/attgroup/change?cat=user&uid= xxxxxxxxxx 似乎能抓取到更多的关注人
> 
> 如：新华社 https://weibo.cn/attgroup/change?cat=user&uid=1699432410
> ![新华视点的所有关注人](https://user-images.githubusercontent.com/48707379/62828339-94f4b900-bb98-11e9-893d-e27c4186e815.jpg)
> 
> 随便试了几个id，从页数来看大多数情况下返回的估计是全部关注人了；唯一的例外是人民日报，显示关注3000+但是只有34页
> https://weibo.cn/attgroup/change?cat=user&uid=2803301701
> ![人民日报的所有关注人](https://user-images.githubusercontent.com/48707379/62828371-94105700-bb99-11e9-9bbf-024af4c5e30e.jpg)

厉害，你是怎么找到这个接口的啊

**Comment by MR3118** [comment]
评论或者是转发实际数远小于理论数，有谁知道具体原因吗？提示是定向转发之类的，但是少的也太多了，特别有些多的，例如原100000条的，实际爬下来的可能只有20000条

**Comment by Cprocc** [comment]
> 评论或者是转发实际数远小于理论数，有谁知道具体原因吗？提示是定向转发之类的，但是少的也太多了，特别有些多的，例如原100000条的，实际爬下来的可能只有20000条

评论下面的评论，也算一条评论

**Comment by Cprocc** [comment]
> 评论或者是转发实际数远小于理论数，有谁知道具体原因吗？提示是定向转发之类的，但是少的也太多了，特别有些多的，例如原100000条的，实际爬下来的可能只有20000条

评论page>51 就访问不到了
