### ISSUE TITLE
19年8月cookie问题

### ISSUE THREAD

**Issue by DQmyth** [nghuyong/WeiboSpider#89]
这两天发现程序不能跑了, 访问都是302状态码, 虽然不会报错, 但是内容提不出来了.检查后发现是cookie的问题, 需要重新运行一下login.py更新一下cookie, 希望对大家有帮助~

**Comment by nghuyong** [comment]
好的，谢谢。
这个cookie是有有效期的，需要定期更新

**Comment by DQmyth** [comment]
是的!
