### ISSUE TITLE
粉丝问题

### ISSUE THREAD

**Issue by 2655398311** [nghuyong/WeiboSpider#90]
你好  我参考您的代码  爬取了一些人的微博 但是粉丝只能爬取四百多个 相差好多  不知道是哪里的问题 想请教下

**Comment by nghuyong** [comment]
对的，粉丝本来就不能完全抓取。这是微博接口本身的限制

**Comment by 2655398311** [comment]
哦哦 谢谢您  有没有什么渠道可以爬取到所有的粉丝，我看到微博手机app可以查看到所有的粉丝，这个您爬过么？

**Comment by nghuyong** [comment]
不存在的。
一个大明星有几千万粉丝，不可能都能看到的。

**Comment by 2655398311** [comment]
哦哦 那就是我理解错了
