### ISSUE TITLE
爬虫什么时候会停

### ISSUE THREAD

**Issue by 2655398311** [nghuyong/WeiboSpider#91]
我想问下您 您的这个爬虫爬虫是爬到什么时候会停 或者是我能给她一个时间么 让他在指定时间段内爬取 大概是这样子的  您这个是已经实现的了么

**Comment by nghuyong** [comment]
可以实现爬虫的调度，需要用Python的实践调度框架
我没有实现

**Comment by 2655398311** [comment]
哦哦 这个就是不会停是吧 那就比如他现在爬到16年的数据了 但是微博本人更新微博了 我又想爬他新更新的微博了 这个怎么办啊

**Comment by nghuyong** [comment]
每天定时抓取

**Comment by 2655398311** [comment]
每天定时抓取 ？ 抱歉啊  代码没太看明白  可以具体一点么  每天什么时间段进行抓取
