### ISSUE TITLE
微博418

### ISSUE THREAD

**Issue by 2655398311** [nghuyong/WeiboSpider#92]
我先问下 这个微博爬虫一直报418，这个是怎么回事啊

**Comment by nghuyong** [comment]
添加一个代理IP试试呢

**Comment by 2655398311** [comment]
您的单机代码里面有用到代理IP么

**Comment by nghuyong** [comment]
没有
你使用单机版请严格按照配置的延迟和并发量，确保爬虫速度不要太快
否则就会被封IP
你可能需要等一段时间，2-3小时，IP才能被解除封锁

**Comment by nghuyong** [comment]
你也可以试试更换一个微博账号

**Comment by 2655398311** [comment]
要不我给他随机睡一段时间。如果是418是不是会导致数据缺失

**Comment by nghuyong** [comment]
是，418会导致数据缺失
不用随机睡眠，你的配置文件
https://github.com/nghuyong/WeiboSpider/blob/simple/sina/settings.py#L18
https://github.com/nghuyong/WeiboSpider/blob/simple/sina/settings.py#L20
这两行不要修改就行，这个速度我测试是不会被封的

**Comment by 2655398311** [comment]
哦哦 我明白了 我现在运行这个代码就会报302  然后就不执行了 就退出执行了

上边的那个问题我是不是加个账号池就会好一点

**Comment by nghuyong** [comment]
是，你想速度更快一点，就参考master分支来构建

**Comment by 2655398311** [comment]
您好 如果我想新建一个数据库写入  是不是把dbname = sina  sina换掉就可以了

**Comment by nghuyong** [comment]
是
