### ISSUE TITLE
账号池+分布式 运行问题

### ISSUE THREAD

**Issue by 2655398311** [nghuyong/WeiboSpider#94]
https://github.com/nghuyong/WeiboSpider

你好 你看下我的这个截图 不知道为什么 配置的是您的账号池+分布式的代码 启动以后一直这样 不知道是怎么回事 ，你可以给我解答下么  谢谢

**Comment by 2655398311** [comment]
![](https://static.dingtalk.com/media/lALPDgQ9q8lHl8TNAd3NBTw_1340_477.png_620x10000q90g.jpg)

**Comment by nghuyong** [comment]
你初始化redis了吗
https://github.com/nghuyong/WeiboSpider/tree/senior#%E5%88%9D%E5%A7%8B%E5%8C%96redis

**Comment by 2655398311** [comment]
做初始化了  您看下这个截图，不知道是为啥



------------------ 原始邮件 ------------------
发件人: "HuYong"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 下午3:00
收件人: "nghuyong/WeiboSpider"<WeiboSpider@noreply.github.com>;
抄送: "杰"<2655398311@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nghuyong/WeiboSpider] 账号池+分布式 运行问题 (#94)




你初始化redis了吗
 https://github.com/nghuyong/WeiboSpider/tree/senior#%E5%88%9D%E5%A7%8B%E5%8C%96redis
