### ISSUE TITLE
mongo数据库的问题

### ISSUE THREAD

**Issue by 854350999** [nghuyong/WeiboSpider#96]
scrapy运行的时候显示no module named pymongo

**Comment by nghuyong** [comment]
你需要安装依赖
https://github.com/nghuyong/WeiboSpider#%E5%85%8B%E9%9A%86%E6%9C%AC%E9%A1%B9%E7%9B%AE--%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96

**Comment by 854350999** [comment]
我把pymongo的包放到项目目录下就可以运行了，应该是我把项目放在环境下一级无法检测到，已经解决了，谢谢大佬的源码
