### ISSUE TITLE
关于IP代理池的问题

### ISSUE THREAD

**Issue by 854350999** [nghuyong/WeiboSpider#97]
老哥 想问一下如何在这个框架里添加这个IP代理池   今天爬虫的时候被反爬了

**Comment by nghuyong** [comment]
https://github.com/nghuyong/WeiboSpider/blob/master/sina/middlewares.py#L53

**Comment by 854350999** [comment]
谢谢大佬分享，想说一下微博cn客户端现在好像只显示50页评论了
