### ISSUE TITLE
关于爬取失败和恢复的问题

### ISSUE THREAD

**Issue by 112798** [nghuyong/WeiboSpider#99]
<p>你好，想请教一下当爬取微博速度过快或者频率过高的时候，会收到http code <b>418</b>，请问该如何处理这个异常？如果不设置相应的爬取间隔，微博服务器将会对这个请求不停的返回418状态码，会导致这个<b>URL</b>的<b>Request</b>重复加入调度队列，降低爬虫的运行速率，能否实现设置该request加入调度队列的间隔，比如说使用time.sleep(60)这样的暂停语句，使得这个<b>Request</b>能够在间隔一定时间之后再被爬虫所执行。</p>  
当然，我觉得也可以设置这个request的优先级，降低它的优先级，来使得这个request在间隔一定时间之后才重新进行爬取，但是这样貌似是不能具体的设置它的爬取间隔，也只是我的一个不成熟的小想法，不知道这样能否实现。

**Comment by nghuyong** [comment]
添加代理池可以解决这个问题

**Comment by 112798** [comment]
了解了，刚刚仔细想了想确实可以通过添加代理池的方式来解决这个问题，多谢。
